import type { TrustedObservation } from './trustedObservationPack';

type SourceFamily =
  | 'california-imr'
  | 'mayo-clinic-connect'
  | 'glp1-coverage'
  | 'mental-health-parity'
  | 'cancer-rare-disease'
  | 'court-lawsuits'
  | 'public-facebook-discovery';

export interface SourceFamilyPack {
  id: SourceFamily;
  name: string;
  strategy: 'automated' | 'manual_review';
  observations: TrustedObservation[];
}

export const SOURCE_FAMILY_PACKS: SourceFamilyPack[] = [
  {
    id: 'california-imr',
    name: 'California IMR / external review sources',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-dmhc-imr-search',
        canonical_url: 'https://www.dmhc.ca.gov/DataResearch/SearchIndependentMedicalReviewDecisions.aspx',
        source_type: 'official_regulatory',
        source_label: 'California DMHC IMR',
        source_weight: 'official_regulatory',
        title: 'California publishes searchable independent medical review decisions',
        raw_text: 'California DMHC publishes searchable independent medical review decisions that show how treatment denials are overturned or upheld after outside review.',
        story_excerpt: 'A rare public source of structured denial outcomes and reversal logic across medical treatment disputes.',
        insurer_raw: 'California health plans',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Independent medical review decisions',
        procedure_normalized: 'Independent medical review',
        denial_reason_raw: 'Treatment denial reviewed by outside independent medical review process',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 95,
        is_low_signal: false,
        fingerprint: 'family-dmhc-imr-search',
      },
      {
        observation_id: 'family-dmhc-overturn-stats',
        canonical_url: 'https://www.dmhc.ca.gov/FileaComplaint/FrequentlyAskedQuestions.aspx',
        source_type: 'official_regulatory',
        source_label: 'California DMHC',
        source_weight: 'official_regulatory',
        title: 'California tracks how often outside reviewers overturn denials',
        raw_text: 'California consumer complaint materials explain the independent medical review process and report that a meaningful share of treatment denials are overturned.',
        story_excerpt: 'Good benchmark source for how often independent review reverses plan denials.',
        insurer_raw: 'California health plans',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'External review and independent medical review',
        procedure_normalized: 'Independent medical review',
        denial_reason_raw: 'Treatment denial taken to outside review and sometimes overturned',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 93,
        is_low_signal: false,
        fingerprint: 'family-dmhc-overturn-stats',
      },
      {
        observation_id: 'family-cdi-imr-advisory',
        canonical_url: 'https://www.insurance.ca.gov/01-consumers/110-health/60-resources/01-imr/upload/imradvisory3.pdf',
        source_type: 'official_regulatory',
        source_label: 'California Department of Insurance',
        source_weight: 'official_regulatory',
        title: 'California IMR advisory explains outside-review rights',
        raw_text: 'California insurance regulators explain the independent medical review process and when consumers can challenge denials through outside review.',
        story_excerpt: 'Useful benchmark for appeal rights, deadlines, and what outside review can overturn.',
        insurer_raw: 'California health plans',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Independent medical review and external appeal',
        procedure_normalized: 'Independent medical review',
        denial_reason_raw: 'Coverage denial challenged through California independent medical review',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 92,
        is_low_signal: false,
        fingerprint: 'family-cdi-imr-advisory',
      },
    ],
  },
  {
    id: 'mayo-clinic-connect',
    name: 'Mayo Clinic Connect denial discussions',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-mayo-bcbs-coverage',
        canonical_url: 'https://connect.mayoclinic.org/discussion/bcbs-has-denied-coverage/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'BCBS denied coverage discussion on Mayo Clinic Connect',
        raw_text: 'Patient discussion on Mayo Clinic Connect about Blue Cross Blue Shield denying coverage and the scramble to keep treatment moving.',
        story_excerpt: 'A public patient narrative about feeling cornered when coverage disappears during active care.',
        insurer_raw: 'Blue Cross Blue Shield',
        insurer_normalized: 'Blue Cross Blue Shield',
        procedure_raw: 'Ongoing specialty treatment coverage',
        procedure_normalized: 'Specialty treatment coverage',
        denial_reason_raw: 'Coverage denied during ongoing care and patient forced to search for options',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 90,
        is_low_signal: false,
        fingerprint: 'family-mayo-bcbs-coverage',
      },
      {
        observation_id: 'family-mayo-denied-benlysta',
        canonical_url: 'https://connect.mayoclinic.org/discussion/denied-benlysta/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Benlysta denial discussion',
        raw_text: 'Mayo Clinic Connect discussion on denied Benlysta coverage, specialty-drug access barriers, and the appeal burden on patients with autoimmune disease.',
        story_excerpt: 'Useful signal for specialty medication denials and the burden of proving necessity over and over.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Benlysta infusion or specialty medication',
        procedure_normalized: 'Prescription medication',
        denial_reason_raw: 'Specialty medication denied or delayed despite ongoing clinical need',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-mayo-denied-benlysta',
      },
      {
        observation_id: 'family-mayo-denied-tobi',
        canonical_url: 'https://connect.mayoclinic.org/discussion/insurance-denied-tobi-inhaled-tobramycin/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Insurance denied inhaled tobramycin',
        raw_text: 'Patient discussion on inhaled tobramycin denial, with medication access interrupted by insurer review.',
        story_excerpt: 'A concrete drug-specific denial example patients can actually recognize and search against.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Inhaled tobramycin medication coverage',
        procedure_normalized: 'Prescription medication',
        denial_reason_raw: 'Medication denied despite physician support',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 87,
        is_low_signal: false,
        fingerprint: 'family-mayo-denied-tobi',
      },
      {
        observation_id: 'family-mayo-insurance-denied-claim',
        canonical_url: 'https://connect.mayoclinic.org/discussion/insurance-denied-my-claim/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Insurance denied my claim discussion',
        raw_text: 'Patient discussion on Mayo Clinic Connect about a denied surgery claim and the need to appeal with physician backing.',
        story_excerpt: 'Useful because it is direct, denial-specific, and tied to a concrete appeal experience rather than vague insurance frustration.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Surgery claim coverage',
        procedure_normalized: 'Surgery',
        denial_reason_raw: 'Claim denied for surgery and patient advised to appeal with physician documentation',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-mayo-insurance-denied-claim',
      },
    ],
  },
  {
    id: 'glp1-coverage',
    name: 'GLP-1 and obesity medication coverage fights',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-zepbound-denied',
        canonical_url: 'https://www.reddit.com/r/Zepbound/comments/1gjf264/insurance_denied_zepbound/',
        source_type: 'public_patient_forum',
        source_label: 'Reddit r/Zepbound',
        source_weight: 'public_patient_forum',
        title: 'Insurance denied Zepbound',
        raw_text: 'Patient reporting direct insurance denial of Zepbound and trying to decode prior authorization and exclusion logic.',
        story_excerpt: 'Strong GLP-1 denial signal around obesity medication access.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Zepbound coverage',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'Weight-loss drug denied through plan exclusion or prior authorization',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 91,
        is_low_signal: false,
        fingerprint: 'family-zepbound-denied',
      },
      {
        observation_id: 'family-zepbound-optumrx-appeal',
        canonical_url: 'https://www.reddit.com/r/Zepbound/comments/1i16n2y/insurance_appeals_optumrx/',
        source_type: 'public_patient_forum',
        source_label: 'Reddit r/Zepbound',
        source_weight: 'public_patient_forum',
        title: 'OptumRx appeals over Zepbound coverage',
        raw_text: 'Public discussion focused on OptumRx and appeals over Zepbound coverage denials.',
        story_excerpt: 'High-value because it links a named payer to a named drug and an appeal pathway.',
        insurer_raw: 'OptumRx',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Zepbound coverage and appeal',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'Prior authorization and formulary barriers for Zepbound under OptumRx',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 94,
        is_low_signal: false,
        fingerprint: 'family-zepbound-optumrx-appeal',
      },
      {
        observation_id: 'family-mounjaro-coverage-community',
        canonical_url: 'https://www.reddit.com/r/Mounjaro/',
        source_type: 'public_patient_forum',
        source_label: 'Reddit r/Mounjaro',
        source_weight: 'public_patient_forum',
        title: 'Mounjaro communities documenting repeat coverage denials',
        raw_text: 'Public patient posts in Mounjaro communities repeatedly describe formulary exclusions, step therapy, and abrupt loss of coverage for GLP-1 medication.',
        story_excerpt: 'Another strong GLP-1 lane because the same denial themes keep repeating across plans and payers.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Mounjaro coverage',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'GLP-1 medication blocked through exclusions, step therapy, or prior authorization',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 86,
        is_low_signal: false,
        fingerprint: 'family-mounjaro-coverage-community',
      },
      {
        observation_id: 'family-ozempic-coverage-community',
        canonical_url: 'https://www.reddit.com/r/Ozempic/',
        source_type: 'public_patient_forum',
        source_label: 'Reddit r/Ozempic',
        source_weight: 'public_patient_forum',
        title: 'Ozempic communities documenting coverage denials',
        raw_text: 'The Ozempic community includes repeated stories about step therapy, prior authorization, and abrupt loss of coverage.',
        story_excerpt: 'Broad but valuable evidence that GLP-1 denials are a recurring consumer fight, not a one-off.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Ozempic coverage',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'Step therapy, prior authorization, and plan exclusions for GLP-1 medication',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 86,
        is_low_signal: false,
        fingerprint: 'family-ozempic-coverage-community',
      },
    ],
  },
  {
    id: 'mental-health-parity',
    name: 'Mental health parity and therapy coverage sources',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-dol-parity',
        canonical_url: 'https://www.dol.gov/agencies/ebsa/laws-and-regulations/laws/mental-health-and-substance-use-disorder-parity',
        source_type: 'official_regulatory',
        source_label: 'Department of Labor',
        source_weight: 'official_regulatory',
        title: 'Mental health parity protections define insurer obligations',
        raw_text: 'Department of Labor parity guidance explains that mental health and addiction treatment cannot be more restrictive than comparable medical benefits.',
        story_excerpt: 'Useful legal benchmark for patients fighting therapy and psychiatry denials.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Therapy, psychiatry, and behavioral health care',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Mental health parity violations and restrictive coverage limits',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'ERISA',
        quality_score: 95,
        is_low_signal: false,
        fingerprint: 'family-dol-parity',
      },
      {
        observation_id: 'family-nami-denials-guide',
        canonical_url: 'https://www.nami.org/nami-news/nami-releases-new-guide-to-help-fight-coverage-denials-of-mental-health-addiction-care/',
        source_type: 'official_regulatory',
        source_label: 'NAMI',
        source_weight: 'official_regulatory',
        title: 'NAMI guide to fighting mental health coverage denials',
        raw_text: 'NAMI guidance on fighting mental health and addiction treatment denials, including how patients are forced out of network or denied needed care.',
        story_excerpt: 'High-value because it speaks directly to therapy and psychiatric care denials patients can fight.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Therapy, psychiatry, and addiction treatment',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Mental health treatment denied or pushed out of network',
        denial_category: 'Out of Network',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 92,
        is_low_signal: false,
        fingerprint: 'family-nami-denials-guide',
      },
      {
        observation_id: 'family-autismspeaks-aba-law',
        canonical_url: 'https://www.autismspeaks.org/advocacy-news/autism-speaks-celebrates-new-california-law-protecting-access-behavioral-health',
        source_type: 'official_regulatory',
        source_label: 'Autism Speaks',
        source_weight: 'official_regulatory',
        title: 'Autism coverage fights over repeated re-diagnosis and ABA access',
        raw_text: 'Autism Speaks describes insurer practices that force repeated autism re-diagnoses to keep ABA and behavioral health treatment covered.',
        story_excerpt: 'High-value benchmark for autism families fighting behavioral health denials and repeated re-authorization burdens.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'ABA therapy and behavioral health treatment',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Repeated re-diagnosis requirement and behavioral health access barriers for autism treatment',
        denial_category: 'Prior Authorization',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 93,
        is_low_signal: false,
        fingerprint: 'family-autismspeaks-aba-law',
      },
      {
        observation_id: 'family-autismspeaks-standards-care',
        canonical_url: 'https://www.autismspeaks.org/advocacy-news/importance-generally-accepted-standards-care',
        source_type: 'official_regulatory',
        source_label: 'Autism Speaks',
        source_weight: 'official_regulatory',
        title: 'Autism care denials framed against generally accepted standards of care',
        raw_text: 'Autism Speaks warns that insurers can narrow medically necessary autism benefits by drifting away from generally accepted standards of care.',
        story_excerpt: 'Strong benchmark material for autism denials labeled as not medically necessary or limited by restrictive standards.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Autism behavioral health treatment',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Autism services restricted by insurer interpretation of medical necessity and standards of care',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 91,
        is_low_signal: false,
        fingerprint: 'family-autismspeaks-standards-care',
      },
      {
        observation_id: 'family-mental-health-america-parity',
        canonical_url: 'https://mhanational.org/issues/access-care',
        source_type: 'official_regulatory',
        source_label: 'Mental Health America',
        source_weight: 'official_regulatory',
        title: 'Mental Health America documents access-to-care barriers',
        raw_text: 'Mental Health America explains how insurer restrictions, provider shortages, and parity gaps block access to therapy and psychiatric care.',
        story_excerpt: 'Helpful benchmark source for therapy, psychiatry, and parity-related coverage barriers.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Therapy and psychiatric care',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Mental health care blocked through restrictive coverage or parity failures',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-mental-health-america-parity',
      },
    ],
  },
  {
    id: 'cancer-rare-disease',
    name: 'Cancer and rare-disease support communities',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-bco-share-denial',
        canonical_url: 'https://community.breastcancer.org/en/discussion/880142/share-your-insurance-claims-denial-story',
        source_type: 'public_patient_forum',
        source_label: 'Breastcancer.org Community',
        source_weight: 'public_patient_forum',
        title: 'Breast cancer patients sharing denial stories',
        raw_text: 'Breast cancer community thread explicitly collecting insurance denial stories and treatment access barriers.',
        story_excerpt: 'A direct “patients like me” style source for oncology denials and appeal outcomes.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Cancer treatment and reconstruction-related care',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Coverage denial or repeated treatment-access barrier during cancer care',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 94,
        is_low_signal: false,
        fingerprint: 'family-bco-share-denial',
      },
      {
        observation_id: 'family-als-nord-poster',
        canonical_url: 'https://www.als.org/sites/default/files/2024-01/ALS-Focus_2023-NORD-Poster.pdf',
        source_type: 'official_regulatory',
        source_label: 'ALS Association / NORD',
        source_weight: 'official_regulatory',
        title: 'ALS denials and appeal burden survey findings',
        raw_text: 'ALS Association and NORD poster summarizing denials, prior authorization burden, and equipment access barriers in ALS care.',
        story_excerpt: 'Rare high-signal evidence about DME and support denials in ALS.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'ALS care and durable medical equipment',
        procedure_normalized: 'ALS care and durable medical equipment',
        denial_reason_raw: 'Prior authorization denial and equipment access barriers in ALS care',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 95,
        is_low_signal: false,
        fingerprint: 'family-als-nord-poster',
      },
      {
        observation_id: 'family-cancercare-insurance',
        canonical_url: 'https://www.cancercare.org/publications/62-understanding_the_cost_of_care_and_your_health_insurance',
        source_type: 'official_regulatory',
        source_label: 'CancerCare',
        source_weight: 'official_regulatory',
        title: 'Cancer coverage barriers around prior auth and claims',
        raw_text: 'CancerCare guidance on claim denials, prior authorization, and treatment affordability in oncology.',
        story_excerpt: 'Useful benchmark source for cancer patients whose treatment or supportive care gets delayed by coverage fights.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Cancer treatment and oncology supportive care',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Claim denial and authorization friction in cancer care',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 89,
        is_low_signal: false,
        fingerprint: 'family-cancercare-insurance',
      },
      {
        observation_id: 'family-alz-healthcare-appeals',
        canonical_url: 'https://www.alz.org/Help-Support/Caregiving/Financial-Legal-Planning/Healthcare-Appeals-for-People-with-Alzheimers-and',
        source_type: 'official_regulatory',
        source_label: "Alzheimer's Association",
        source_weight: 'official_regulatory',
        title: 'Health care appeals for people with Alzheimer’s and other dementias',
        raw_text: 'The Alzheimer’s Association explains how caregivers can appeal denials when dementia-related services, treatment, or medication are refused as not medically necessary or too frequent.',
        story_excerpt: 'Strong benchmark material for dementia-care denials and caregiver appeal strategy.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Dementia care services and medication coverage',
        procedure_normalized: 'Dementia care and medication coverage',
        denial_reason_raw: 'Dementia-related treatment or medication denied as not medically necessary or too frequent',
        denial_category: 'Medical Necessity',
        plan_type: 'Medicare',
        erisa_status: 'Non-ERISA',
        quality_score: 94,
        is_low_signal: false,
        fingerprint: 'family-alz-healthcare-appeals',
      },
      {
        observation_id: 'family-alz-medicare-refuses-pay',
        canonical_url: 'https://www.alz.org/media/documents/alzheimers-dementia-medicare-refuse-to-pay-ts.pdf',
        source_type: 'official_regulatory',
        source_label: "Alzheimer's Association",
        source_weight: 'official_regulatory',
        title: 'What to do if Medicare refuses to pay in dementia care',
        raw_text: 'Alzheimer’s Association guidance for caregivers facing Medicare refusals to pay for medical services or procedures tied to dementia care.',
        story_excerpt: 'Useful because it translates denial notices into concrete appeal steps for dementia-related care.',
        insurer_raw: 'Medicare',
        insurer_normalized: 'Medicare',
        procedure_raw: 'Medical service or procedure related to dementia care',
        procedure_normalized: 'Dementia care and medication coverage',
        denial_reason_raw: 'Medicare refuses to pay for service or procedure and caregiver must appeal',
        denial_category: 'Administrative',
        plan_type: 'Medicare',
        erisa_status: 'Non-ERISA',
        quality_score: 92,
        is_low_signal: false,
        fingerprint: 'family-alz-medicare-refuses-pay',
      },
    ],
  },
  {
    id: 'court-lawsuits',
    name: 'Court and lawsuit intelligence',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-stat-navihealth-lawsuit',
        canonical_url: 'https://www.statnews.com/2023/11/14/unitedhealth-navihealth-lawsuit-medicare-advantage/',
        source_type: 'investigative',
        source_label: 'STAT',
        source_weight: 'investigative',
        title: 'UnitedHealth / NaviHealth lawsuit over Medicare Advantage denials',
        raw_text: 'Investigative reporting on lawsuits claiming algorithmic post-acute care denials and premature cutoffs under Medicare Advantage.',
        story_excerpt: 'High-value systemic evidence tying a named insurer to repeat denial tactics and litigation.',
        insurer_raw: 'UnitedHealth / NaviHealth',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Post-acute and skilled nursing coverage',
        procedure_normalized: 'Post-acute care coverage',
        denial_reason_raw: 'Algorithmic or accelerated denial of post-acute care under Medicare Advantage',
        denial_category: 'Medical Necessity',
        plan_type: 'Medicare Advantage',
        erisa_status: 'Non-ERISA',
        quality_score: 96,
        is_low_signal: false,
        fingerprint: 'family-stat-navihealth-lawsuit',
      },
      {
        observation_id: 'family-courtlistener-search-united',
        canonical_url: 'https://www.courtlistener.com/help/search-operators/',
        source_type: 'investigative',
        source_label: 'CourtListener / legal search',
        source_weight: 'investigative',
        title: 'CourtListener can be used to monitor insurer denial litigation',
        raw_text: 'CourtListener search and API infrastructure make it possible to monitor lawsuits and docket activity around prior authorization, parity, and insurer denials.',
        story_excerpt: 'Not a patient story, but a high-value legal intelligence source for repeated insurer tactics and class-action risk.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Denial-related litigation and dockets',
        procedure_normalized: 'Denial-related litigation',
        denial_reason_raw: 'Litigation alleging insurer denial tactics or parity violations',
        denial_category: 'Administrative',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 82,
        is_low_signal: false,
        fingerprint: 'family-courtlistener-search-united',
      },
      {
        observation_id: 'family-propublica-autism-treatment',
        canonical_url: 'https://www.propublica.org/article/unitedhealth-strategically-limiting-autism-treatment',
        source_type: 'investigative',
        source_label: 'ProPublica',
        source_weight: 'investigative',
        title: 'Investigative reporting on autism-treatment limits',
        raw_text: 'Investigative reporting on how a major insurer limited autism treatment, creating a strong public-interest record around repeat behavioral-health denials.',
        story_excerpt: 'High-value precedent material because it connects a named insurer, a named treatment area, and a broader denial pattern.',
        insurer_raw: 'UnitedHealthcare',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Autism treatment and ABA therapy',
        procedure_normalized: 'ABA therapy',
        denial_reason_raw: 'Behavioral-health treatment restricted through internal insurer limits',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 95,
        is_low_signal: false,
        fingerprint: 'family-propublica-autism-treatment',
      },
    ],
  },
  {
    id: 'public-facebook-discovery',
    name: 'Public Facebook discovery lane',
    strategy: 'manual_review',
    observations: [
      {
        observation_id: 'family-facebook-oac-public',
        canonical_url: 'https://www.facebook.com/obesityaction/',
        source_type: 'social_chatter',
        source_label: 'Facebook public advocacy page',
        source_weight: 'social_chatter',
        title: 'Public social discussion around obesity coverage barriers',
        raw_text: 'Public advocacy-page discussions can surface GLP-1 and obesity-treatment coverage complaints, but they require manual review before promotion.',
        story_excerpt: 'This lane is for discovery only until we have cleaner public-post harvesting rules.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'GLP-1 medication and obesity treatment',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'Public social discussion about coverage denial or exclusion',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 60,
        is_low_signal: false,
        fingerprint: 'family-facebook-oac-public',
      },
      {
        observation_id: 'family-facebook-nami-public',
        canonical_url: 'https://www.facebook.com/NAMI/',
        source_type: 'social_chatter',
        source_label: 'Facebook public advocacy page',
        source_weight: 'social_chatter',
        title: 'Public social discussion around mental health coverage denials',
        raw_text: 'Public advocacy-page discussions can surface therapy and psychiatry coverage barriers, but they should stay in a manual-review lane unless a post is clearly public and denial-specific.',
        story_excerpt: 'A cautious public-social lane for discovery, not blind promotion.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Therapy services and psychiatric care',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Mental health coverage denied or restricted',
        denial_category: 'Out of Network',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 58,
        is_low_signal: false,
        fingerprint: 'family-facebook-nami-public',
      },
      {
        observation_id: 'family-facebook-autismspeaks-public',
        canonical_url: 'https://www.facebook.com/autismspeaks/',
        source_type: 'social_chatter',
        source_label: 'Facebook public advocacy page',
        source_weight: 'social_chatter',
        title: 'Public social discussion around autism-treatment coverage',
        raw_text: 'Public advocacy-page discussions can surface ABA therapy and autism-treatment coverage barriers, but this lane stays in manual review unless the post is clearly public and denial-specific.',
        story_excerpt: 'Discovery lane for autism-treatment complaints on clearly public advocacy pages.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'ABA therapy and autism-treatment coverage',
        procedure_normalized: 'ABA therapy',
        denial_reason_raw: 'Public social discussion about autism-treatment denials or insurer limits',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 58,
        is_low_signal: false,
        fingerprint: 'family-facebook-autismspeaks-public',
      },
    ],
  },
];

export const SOURCE_FAMILY_OBSERVATIONS: TrustedObservation[] = SOURCE_FAMILY_PACKS.flatMap((family) => family.observations);
