import type { TrustedObservation } from './trustedObservationPack';

type SourceFamily =
  | 'california-imr'
  | 'aarp-medicare-insurance'
  | 'mayo-clinic-connect'
  | 'glp1-coverage'
  | 'mental-health-parity'
  | 'cancer-rare-disease'
  | 'access-advocacy-research'
  | 'court-lawsuits'
  | 'public-facebook-discovery'
  | 'state-review-datasets';

export interface SourceFamilyPack {
  id: SourceFamily;
  name: string;
  strategy: 'automated' | 'manual_review';
  observations: TrustedObservation[];
}

export const SOURCE_FAMILY_PACKS: SourceFamilyPack[] = [
  {
    id: 'access-advocacy-research',
    name: 'Access advocacy, patient assistance, and denial research',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-paf-pan-totalassist',
        canonical_url: 'https://www.patientadvocate.org/explore-our-resources/patient-advocate-foundation-and-pan-foundation-merge-to-expand-patient-support/',
        source_type: 'official_regulatory',
        source_label: 'PAF / PAN TotalAssist',
        source_weight: 'official_regulatory',
        title: 'PAF and PAN merge to expand TotalAssist support for access barriers',
        raw_text: 'Patient Advocate Foundation and PAN Foundation merged in March 2026 to expand TotalAssist and patient support for coverage barriers, affordability problems, and treatment access breakdowns.',
        story_excerpt: 'A strong public-interest source because it is built around real patient access barriers and how people get unblocked when coverage fails.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Treatment access and patient assistance navigation',
        procedure_normalized: 'Treatment access and patient assistance',
        denial_reason_raw: 'Coverage barrier or affordability failure blocked needed care until outside advocacy intervened',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 91,
        is_low_signal: false,
        fingerprint: 'family-paf-pan-totalassist',
      },
      {
        observation_id: 'family-kff-bill-of-the-month',
        canonical_url: 'https://kffhealthnews.org/news/tag/bill-of-the-month/',
        source_type: 'investigative',
        source_label: 'KFF Health News Bill of the Month',
        source_weight: 'investigative',
        title: 'Bill of the Month surfaces insurer denials and impossible bills through patient storytelling',
        raw_text: 'KFF Health News Bill of the Month crowdsources patient stories about surprise bills, denied coverage, and impossible reimbursement fights that expose systemic insurer failures.',
        story_excerpt: 'A very strong narrative source because it turns scattered patient pain into documented, reported evidence with accountability built in.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Denied coverage and surprise billing disputes',
        procedure_normalized: 'Claims processing disputes',
        denial_reason_raw: 'Coverage denied or shifted onto the patient through billing complexity and insurer decision making',
        denial_category: 'Administrative',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 93,
        is_low_signal: false,
        fingerprint: 'family-kff-bill-of-the-month',
      },
      {
        observation_id: 'family-dollar-for-charity-care',
        canonical_url: 'https://dollarfor.org/',
        source_type: 'official_regulatory',
        source_label: 'Dollar For',
        source_weight: 'official_regulatory',
        title: 'Dollar For helps patients fight hospital bills through charity care rights',
        raw_text: 'Dollar For automates charity care applications and helps patients challenge hospital billing burdens when insurance or assistance systems fail to protect them.',
        story_excerpt: 'Not a classic prior-auth source, but highly relevant to what happens after people are abandoned by coverage and left with impossible bills.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Hospital bill relief and charity care',
        procedure_normalized: 'Hospital billing relief',
        denial_reason_raw: 'Insurance and hospital assistance failures left the patient carrying bills they may have had legal rights to reduce or waive',
        denial_category: 'Administrative',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 86,
        is_low_signal: false,
        fingerprint: 'family-dollar-for-charity-care',
      },
      {
        observation_id: 'family-fair-health-help-insurance-issues',
        canonical_url: 'https://www.fairhealthconsumer.org/insurance-basics/your-health-plan/help-with-insurance-issues',
        source_type: 'official_regulatory',
        source_label: 'FAIR Health Consumer',
        source_weight: 'official_regulatory',
        title: 'FAIR Health explains how patients can fight insurance issues and denials',
        raw_text: 'FAIR Health Consumer explains how to respond to denials, work through internal and external appeals, and understand the health plan rules that insurers rely on.',
        story_excerpt: 'A useful public-interest guide because it translates plan rules into patient action and appeal logic.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Appeals and insurance issue resolution',
        procedure_normalized: 'Claims processing disputes',
        denial_reason_raw: 'Insurer denied or restricted coverage and patient must navigate internal and external review options',
        denial_category: 'Administrative',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 89,
        is_low_signal: false,
        fingerprint: 'family-fair-health-help-insurance-issues',
      },
      {
        observation_id: 'family-commonwealth-coverage-denials',
        canonical_url: 'https://www.commonwealthfund.org/publications/issue-briefs/2024/aug/unforeseen-health-care-bills-coverage-denials-by-insurers',
        source_type: 'official_regulatory',
        source_label: 'Commonwealth Fund',
        source_weight: 'official_regulatory',
        title: 'Commonwealth Fund documents surprise bills and insurer coverage denials',
        raw_text: 'Commonwealth Fund research documents how coverage denials and unforeseen health care bills financially destabilize patients and expose weaknesses in insurer accountability.',
        story_excerpt: 'Strong benchmark material for framing the human and financial cost of denials at a national level.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Coverage denials and unforeseen medical bills',
        procedure_normalized: 'Claims processing disputes',
        denial_reason_raw: 'Coverage denied or shifted to patients through insurer billing and reimbursement failures',
        denial_category: 'Administrative',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 90,
        is_low_signal: false,
        fingerprint: 'family-commonwealth-coverage-denials',
      },
      {
        observation_id: 'family-valuepenguin-denials-appeals',
        canonical_url: 'https://www.valuepenguin.com/health-insurance-claim-denials-and-appeals',
        source_type: 'official_regulatory',
        source_label: 'ValuePenguin',
        source_weight: 'official_regulatory',
        title: 'ValuePenguin quantifies health insurance claim denials and appeals',
        raw_text: 'ValuePenguin summarizes denial and appeal data to show how often claims are denied, how rarely patients appeal, and how uneven the outcomes can be across the system.',
        story_excerpt: 'Useful as a benchmark layer to help explain why patients need a stronger data-backed appeal path.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Health insurance claim denials and appeals',
        procedure_normalized: 'Claims processing disputes',
        denial_reason_raw: 'Claims denied and rarely appealed despite the availability of formal review rights',
        denial_category: 'Administrative',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 84,
        is_low_signal: false,
        fingerprint: 'family-valuepenguin-denials-appeals',
      },
      {
        observation_id: 'family-cancer-support-community-prior-auth',
        canonical_url: 'https://www.cancersupportcommunity.org/',
        source_type: 'official_regulatory',
        source_label: 'Cancer Support Community',
        source_weight: 'official_regulatory',
        title: 'Cancer Support Community provides prior authorization and appeals support',
        raw_text: 'Cancer Support Community gives patients tools for handling prior authorization, treatment delays, and insurer barriers that interrupt cancer care.',
        story_excerpt: 'A strong oncology access source because it directly addresses treatment delays and appeal behavior around prior authorization.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Cancer prior authorization and treatment approval',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Cancer treatment delayed or denied through prior authorization and administrative insurer barriers',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 90,
        is_low_signal: false,
        fingerprint: 'family-cancer-support-community-prior-auth',
      },
      {
        observation_id: 'family-jdrf-insulin-access',
        canonical_url: 'https://www.breakthrought1d.org/advocacy/coverage-and-reimbursement/',
        source_type: 'official_regulatory',
        source_label: 'JDRF / Breakthrough T1D',
        source_weight: 'official_regulatory',
        title: 'JDRF tracks insulin, CGM, and diabetes-device coverage barriers',
        raw_text: 'Breakthrough T1D advocacy materials focus on insurance coverage, reimbursement, prior authorization, and access barriers for insulin, CGMs, and diabetes devices.',
        story_excerpt: 'A high-value diabetes-access lane because the payer language around CGMs, insulin, and device supplies often repeats across plans.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Insulin, CGM, and diabetes device coverage',
        procedure_normalized: 'Insulin and diabetes technology coverage',
        denial_reason_raw: 'Diabetes medication or device access denied, delayed, or constrained by prior authorization and reimbursement rules',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 92,
        is_low_signal: false,
        fingerprint: 'family-jdrf-insulin-access',
      },
      {
        observation_id: 'family-t1international-insulin-advocacy',
        canonical_url: 'https://www.t1international.com/',
        source_type: 'official_regulatory',
        source_label: 'T1International',
        source_weight: 'official_regulatory',
        title: 'T1International documents insulin access failures and payer pressure',
        raw_text: 'T1International advocacy focuses on insulin affordability, access failures, coverage gaps, and the structural barriers that leave people rationing or delaying diabetes care.',
        story_excerpt: 'A high-signal access lane that can help us connect diabetes coverage failures to broader insurer and plan behavior.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Insulin access and diabetes treatment coverage',
        procedure_normalized: 'Insulin and diabetes technology coverage',
        denial_reason_raw: 'Insulin or diabetes treatment access blocked through coverage exclusions, cost barriers, or payer restrictions',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-t1international-insulin-advocacy',
      },
    ],
  },
  {
    id: 'state-review-datasets',
    name: 'State review and denied-claims datasets',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-nevada-denied-claims',
        canonical_url: 'https://doi.nv.gov/Insurers/Life_and_Health/Denied_Claims/',
        source_type: 'official_regulatory',
        source_label: 'Nevada Division of Insurance',
        source_weight: 'official_regulatory',
        title: 'Nevada publishes denied claims and appeal information',
        raw_text: 'Nevada insurance regulators publish denied-claims reporting and complaint information that helps track insurer behavior and consumer remedies.',
        story_excerpt: 'A higher-fidelity regulatory source because it is explicitly about denied claims rather than generic insurance frustration.',
        insurer_raw: 'Nevada health insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Denied claims and appeals reporting',
        procedure_normalized: 'Claims processing disputes',
        denial_reason_raw: 'Denied claims and appeals outcomes tracked by state insurance regulators',
        denial_category: 'Administrative',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 92,
        is_low_signal: false,
        fingerprint: 'family-nevada-denied-claims',
      },
      {
        observation_id: 'family-texas-external-review',
        canonical_url: 'https://www.tdi.texas.gov/consumer/cpmlhhp.html',
        source_type: 'official_regulatory',
        source_label: 'Texas Department of Insurance',
        source_weight: 'official_regulatory',
        title: 'Texas explains external review rights for health denials',
        raw_text: 'Texas insurance regulators explain when consumers can push health denials into external review and how medical necessity disputes can be reversed.',
        story_excerpt: 'Another higher-fidelity state source because it frames denials around concrete appeal rights and review outcomes.',
        insurer_raw: 'Texas health insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'External review of health denials',
        procedure_normalized: 'Independent medical review',
        denial_reason_raw: 'Health denial escalated to external review under state consumer protections',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 91,
        is_low_signal: false,
        fingerprint: 'family-texas-external-review',
      },
      {
        observation_id: 'family-calpers-independent-review',
        canonical_url: 'https://www.calpers.ca.gov/page/active-members/health-benefits/appeals-and-complaints',
        source_type: 'official_regulatory',
        source_label: 'CalPERS Health Benefits',
        source_weight: 'official_regulatory',
        title: 'CalPERS explains appeals, complaints, and independent review',
        raw_text: 'CalPERS explains how members can challenge denials, file complaints, and push health-benefit disputes into independent review.',
        story_excerpt: 'High-fidelity benchmark material because it is explicit about what to do after a denial and how outside review works.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Independent review and health benefit appeals',
        procedure_normalized: 'Independent medical review',
        denial_reason_raw: 'Denied health benefit or treatment request challenged through complaint or outside review',
        denial_category: 'Medical Necessity',
        plan_type: 'Employer Sponsored',
        erisa_status: 'Unknown',
        quality_score: 90,
        is_low_signal: false,
        fingerprint: 'family-calpers-independent-review',
      },
    ],
  },
  {
    id: 'california-imr',
    name: 'California IMR / external review sources',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-dmhc-imr-search',
        canonical_url: 'https://www.dmhc.ca.gov/DataResearch/SearchIndependentMedicalReviewDecisions.aspx',
        source_type: 'official_regulatory',
        source_label: 'California DMHC IMR',
        source_weight: 'official_regulatory',
        title: 'California publishes searchable independent medical review decisions',
        raw_text: 'California DMHC publishes searchable independent medical review decisions that show how treatment denials are overturned or upheld after outside review.',
        story_excerpt: 'A rare public source of structured denial outcomes and reversal logic across medical treatment disputes.',
        insurer_raw: 'California health plans',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Independent medical review decisions',
        procedure_normalized: 'Independent medical review',
        denial_reason_raw: 'Treatment denial reviewed by outside independent medical review process',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 95,
        is_low_signal: false,
        fingerprint: 'family-dmhc-imr-search',
      },
      {
        observation_id: 'family-dmhc-overturn-stats',
        canonical_url: 'https://www.dmhc.ca.gov/FileaComplaint/FrequentlyAskedQuestions.aspx',
        source_type: 'official_regulatory',
        source_label: 'California DMHC',
        source_weight: 'official_regulatory',
        title: 'California tracks how often outside reviewers overturn denials',
        raw_text: 'California consumer complaint materials explain the independent medical review process and report that a meaningful share of treatment denials are overturned.',
        story_excerpt: 'Good benchmark source for how often independent review reverses plan denials.',
        insurer_raw: 'California health plans',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'External review and independent medical review',
        procedure_normalized: 'Independent medical review',
        denial_reason_raw: 'Treatment denial taken to outside review and sometimes overturned',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 93,
        is_low_signal: false,
        fingerprint: 'family-dmhc-overturn-stats',
      },
      {
        observation_id: 'family-cdi-imr-advisory',
        canonical_url: 'https://www.insurance.ca.gov/01-consumers/110-health/60-resources/01-imr/upload/imradvisory3.pdf',
        source_type: 'official_regulatory',
        source_label: 'California Department of Insurance',
        source_weight: 'official_regulatory',
        title: 'California IMR advisory explains outside-review rights',
        raw_text: 'California insurance regulators explain the independent medical review process and when consumers can challenge denials through outside review.',
        story_excerpt: 'Useful benchmark for appeal rights, deadlines, and what outside review can overturn.',
        insurer_raw: 'California health plans',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Independent medical review and external appeal',
        procedure_normalized: 'Independent medical review',
        denial_reason_raw: 'Coverage denial challenged through California independent medical review',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 92,
        is_low_signal: false,
        fingerprint: 'family-cdi-imr-advisory',
      },
    ],
  },
  {
    id: 'aarp-medicare-insurance',
    name: 'AARP Medicare insurance denial and appeal discussions',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-aarp-unfair-denial-claim',
        canonical_url: 'https://community.aarp.org/t5/Medicare-Insurance/Unfair-denial-of-claim-by-AARP-United-Healthcare/td-p/2568247',
        source_type: 'public_patient_forum',
        source_label: 'AARP Medicare Insurance Forum',
        source_weight: 'public_patient_forum',
        title: 'AARP member describes unfair denial of claim by AARP UnitedHealthcare',
        raw_text: 'AARP Medicare forum thread describing a UnitedHealthcare claim denial after coordination-of-benefits confusion and a long appeals fight.',
        story_excerpt: 'A concrete Medicare denial story with a named payer, a denied claim, and a real appeal timeline.',
        insurer_raw: 'AARP United Healthcare',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Medicare claim payment after coordination of benefits',
        procedure_normalized: 'Claims processing disputes',
        denial_reason_raw: 'Claim denied after timing and coordination-of-benefits dispute despite patient appeal effort',
        denial_category: 'Administrative',
        plan_type: 'Medicare Advantage',
        erisa_status: 'Non-ERISA',
        quality_score: 90,
        is_low_signal: false,
        fingerprint: 'family-aarp-unfair-denial-claim',
      },
      {
        observation_id: 'family-aarp-medicare-coverage-denied',
        canonical_url: 'https://community.aarp.org/t5/Medicare-Insurance/Medicare/td-p/2515522',
        source_type: 'public_patient_forum',
        source_label: 'AARP Medicare Insurance Forum',
        source_weight: 'public_patient_forum',
        title: 'Patient says coverage was denied and no clear denial notice appeared',
        raw_text: 'AARP Medicare forum discussion about being told coverage was denied while the file appeared blank and no clear denial notice was visible.',
        story_excerpt: 'Useful because it captures the confusion and administrative opacity patients face even before they can start an appeal.',
        insurer_raw: 'UnitedHealthcare supplemental Medicare insurance',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Supplemental Medicare coverage enrollment and claim handling',
        procedure_normalized: 'Claims processing disputes',
        denial_reason_raw: 'Coverage denied without a clear notice or explanation in the patient file',
        denial_category: 'Administrative',
        plan_type: 'Medicare Supplement',
        erisa_status: 'Non-ERISA',
        quality_score: 87,
        is_low_signal: false,
        fingerprint: 'family-aarp-medicare-coverage-denied',
      },
      {
        observation_id: 'family-aarp-appeal-denied-claim',
        canonical_url: 'https://community.aarp.org/t5/Caregiving/How-to-Appeal-Denied-Health-Insurance-Claims/m-p/2048606',
        source_type: 'public_patient_forum',
        source_label: 'AARP Medicare Insurance Forum',
        source_weight: 'public_patient_forum',
        title: 'AARP caregiving thread on how to appeal denied health insurance claims',
        raw_text: 'AARP caregiving discussion focused on denied health insurance claims, what information the denial letter reveals, and how to appeal effectively.',
        story_excerpt: 'High-value because it is denial-specific and appeal-specific, not just general insurance frustration.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Denied health insurance claims and appeals',
        procedure_normalized: 'Claims processing disputes',
        denial_reason_raw: 'Health claim denied and appeal strategy depends on understanding the exact reason and deadline',
        denial_category: 'Administrative',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 86,
        is_low_signal: false,
        fingerprint: 'family-aarp-appeal-denied-claim',
      },
      {
        observation_id: 'family-aarp-supplement-not-paid',
        canonical_url: 'https://community.aarp.org/t5/Medicare-Insurance/Medicare-amp-Supplement/td-p/2436753',
        source_type: 'public_patient_forum',
        source_label: 'AARP Medicare Insurance Forum',
        source_weight: 'public_patient_forum',
        title: 'AARP member describes service Medicare and supplement would not pay',
        raw_text: 'AARP Medicare forum thread about a service not being paid, the need to trace the exact denial reason, and a year-long appeal backed by detailed documentation.',
        story_excerpt: 'A strong example of how older patients win only after persistent documentation and escalation.',
        insurer_raw: 'Medicare and Medigap',
        insurer_normalized: 'Medicare',
        procedure_raw: 'Medical service denied under Medicare and supplement coverage',
        procedure_normalized: 'Claims processing disputes',
        denial_reason_raw: 'Service denied because Medicare would not pay and supplement coverage could not attach until the underlying dispute was fixed',
        denial_category: 'Administrative',
        plan_type: 'Medicare Supplement',
        erisa_status: 'Non-ERISA',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-aarp-supplement-not-paid',
      },
      {
        observation_id: 'family-aarp-uhc-should-not-sponsored',
        canonical_url: 'https://community.aarp.org/t5/Medicare-Insurance/United-Healthcare-Should-not-be-sponsored-by-AARP/m-p/2658322',
        source_type: 'public_patient_forum',
        source_label: 'AARP Medicare Insurance Forum',
        source_weight: 'public_patient_forum',
        title: 'AARP members criticize UnitedHealthcare denial culture and urge appeals',
        raw_text: 'AARP Medicare thread criticizing UnitedHealthcare for denying needed care and urging patients to file appeals or complaints with Medicare.',
        story_excerpt: 'A useful signal for how denial fatigue and distrust show up in Medicare Advantage discussions.',
        insurer_raw: 'United Health Care',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Medicare Advantage treatment denials',
        procedure_normalized: 'Medicare treatment authorization',
        denial_reason_raw: 'Needed care denied under managed care review and patients pushed toward appeals and complaints',
        denial_category: 'Prior Authorization',
        plan_type: 'Medicare Advantage',
        erisa_status: 'Non-ERISA',
        quality_score: 84,
        is_low_signal: false,
        fingerprint: 'family-aarp-uhc-should-not-sponsored',
      },
      {
        observation_id: 'family-aarp-uhc-prior-auth-testing',
        canonical_url: 'https://community.aarp.org/t5/Medicare-Insurance/Traditional-Medicare-Prior-Approvals-Testing/m-p/2643060',
        source_type: 'public_patient_forum',
        source_label: 'AARP Medicare Insurance Forum',
        source_weight: 'public_patient_forum',
        title: 'AARP members discuss prior approvals and testing denials under Medicare rules',
        raw_text: 'AARP Medicare discussion focused on prior approvals for diagnostic testing, repeated denials, and the confusion patients face when managed-care rules collide with Medicare expectations.',
        story_excerpt: 'High-fidelity because it is directly about testing denials, prior approval barriers, and what older patients have to prove to get care.',
        insurer_raw: 'UnitedHealthcare Medicare Advantage',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Diagnostic testing and prior approval',
        procedure_normalized: 'Diagnostic testing',
        denial_reason_raw: 'Diagnostic testing blocked pending prior authorization and Medicare Advantage review rules',
        denial_category: 'Prior Authorization',
        plan_type: 'Medicare Advantage',
        erisa_status: 'Non-ERISA',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-aarp-uhc-prior-auth-testing',
      },
      {
        observation_id: 'family-aarp-medicare-appeal-rights',
        canonical_url: 'https://community.aarp.org/t5/Medicare-Insurance/United-Healthcare/m-p/2604984',
        source_type: 'public_patient_forum',
        source_label: 'AARP Medicare Insurance Forum',
        source_weight: 'public_patient_forum',
        title: 'AARP thread on UnitedHealthcare denials and what Medicare members can do next',
        raw_text: 'AARP Medicare members compare UnitedHealthcare denial experiences, complaints, and what happens when repeated calls and plan explanations still do not resolve the dispute.',
        story_excerpt: 'Useful because it combines a named payer, Medicare plan context, and concrete escalation behavior instead of vague frustration.',
        insurer_raw: 'UnitedHealthcare',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Medicare Advantage denial and appeal escalation',
        procedure_normalized: 'Medicare treatment authorization',
        denial_reason_raw: 'Needed care denied under Medicare Advantage and patient pushed toward formal complaints and escalation',
        denial_category: 'Administrative',
        plan_type: 'Medicare Advantage',
        erisa_status: 'Non-ERISA',
        quality_score: 87,
        is_low_signal: false,
        fingerprint: 'family-aarp-medicare-appeal-rights',
      },
    ],
  },
  {
    id: 'mayo-clinic-connect',
    name: 'Mayo Clinic Connect denial discussions',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-mayo-bcbs-coverage',
        canonical_url: 'https://connect.mayoclinic.org/discussion/bcbs-has-denied-coverage/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'BCBS denied coverage discussion on Mayo Clinic Connect',
        raw_text: 'Patient discussion on Mayo Clinic Connect about Blue Cross Blue Shield denying coverage and the scramble to keep treatment moving.',
        story_excerpt: 'A public patient narrative about feeling cornered when coverage disappears during active care.',
        insurer_raw: 'Blue Cross Blue Shield',
        insurer_normalized: 'Blue Cross Blue Shield',
        procedure_raw: 'Ongoing specialty treatment coverage',
        procedure_normalized: 'Specialty treatment coverage',
        denial_reason_raw: 'Coverage denied during ongoing care and patient forced to search for options',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 90,
        is_low_signal: false,
        fingerprint: 'family-mayo-bcbs-coverage',
      },
      {
        observation_id: 'family-mayo-denied-benlysta',
        canonical_url: 'https://connect.mayoclinic.org/discussion/denied-benlysta/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Benlysta denial discussion',
        raw_text: 'Mayo Clinic Connect discussion on denied Benlysta coverage, specialty-drug access barriers, and the appeal burden on patients with autoimmune disease.',
        story_excerpt: 'Useful signal for specialty medication denials and the burden of proving necessity over and over.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Benlysta infusion or specialty medication',
        procedure_normalized: 'Prescription medication',
        denial_reason_raw: 'Specialty medication denied or delayed despite ongoing clinical need',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-mayo-denied-benlysta',
      },
      {
        observation_id: 'family-mayo-denied-tobi',
        canonical_url: 'https://connect.mayoclinic.org/discussion/insurance-denied-tobi-inhaled-tobramycin/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Insurance denied inhaled tobramycin',
        raw_text: 'Patient discussion on inhaled tobramycin denial, with medication access interrupted by insurer review.',
        story_excerpt: 'A concrete drug-specific denial example patients can actually recognize and search against.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Inhaled tobramycin medication coverage',
        procedure_normalized: 'Prescription medication',
        denial_reason_raw: 'Medication denied despite physician support',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 87,
        is_low_signal: false,
        fingerprint: 'family-mayo-denied-tobi',
      },
      {
        observation_id: 'family-mayo-insurance-denied-claim',
        canonical_url: 'https://connect.mayoclinic.org/discussion/insurance-denied-my-claim/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Insurance denied my claim discussion',
        raw_text: 'Patient discussion on Mayo Clinic Connect about a denied surgery claim and the need to appeal with physician backing.',
        story_excerpt: 'Useful because it is direct, denial-specific, and tied to a concrete appeal experience rather than vague insurance frustration.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Surgery claim coverage',
        procedure_normalized: 'Surgery',
        denial_reason_raw: 'Claim denied for surgery and patient advised to appeal with physician documentation',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-mayo-insurance-denied-claim',
      },
      {
        observation_id: 'family-mayo-insurance-stopped-medication',
        canonical_url: 'https://connect.mayoclinic.org/discussion/insurance-stopped-my-medication/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Patient says insurance stopped Forteo after two failed appeals',
        raw_text: 'Mayo Clinic Connect discussion about Tricare stopping Forteo coverage despite specialist support and two failed appeals.',
        story_excerpt: 'Very useful because it names the medication, the payer, the failed appeals, and the practical harm.',
        insurer_raw: 'Tricare',
        insurer_normalized: 'Tricare',
        procedure_raw: 'Forteo medication coverage',
        procedure_normalized: 'Prescription medication',
        denial_reason_raw: 'Medication coverage cut off despite specialist support and repeated appeals',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Tricare',
        erisa_status: 'Non-ERISA',
        quality_score: 92,
        is_low_signal: false,
        fingerprint: 'family-mayo-insurance-stopped-medication',
      },
      {
        observation_id: 'family-mayo-ct-retroactive-denial',
        canonical_url: 'https://connect.mayoclinic.org/discussion/ct-scan-retroactively-denied-by-insurance/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Highmark through eviCore retroactively denied a CT scan after it was completed',
        raw_text: 'Mayo Clinic Connect discussion about Highmark through eviCore retroactively denying a CT scan and 3D imaging for not enough clinical detail after the test had already been done.',
        story_excerpt: 'Strong because it names the payer, the review vendor, the imaging fight, and the exact medical-necessity rationale.',
        insurer_raw: 'Highmark through eviCore',
        insurer_normalized: 'Blue Cross Blue Shield',
        procedure_raw: 'CT scan and 3D imaging',
        procedure_normalized: 'CT scan',
        denial_reason_raw: 'CT scan retroactively denied for allegedly insufficient clinical detail to prove medical necessity',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 93,
        is_low_signal: false,
        fingerprint: 'family-mayo-ct-retroactive-denial',
      },
      {
        observation_id: 'family-mayo-getting-approval-provenge',
        canonical_url: 'https://connect.mayoclinic.org/discussion/getting-approval-from-insurance-companies/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Patient describes winning a Provenge appeal after repeated denials',
        raw_text: 'Mayo Clinic Connect discussion about getting approval from insurance companies, including a Provenge denial that was reversed only after a formal hearing and detailed written preparation.',
        story_excerpt: 'Excellent appeal precedent because it explains what finally changed the insurer response.',
        insurer_raw: 'PPO insurance plan',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Provenge treatment coverage',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Treatment denied and then appealed through increasingly formal review stages until approval',
        denial_category: 'Medical Necessity',
        plan_type: 'PPO',
        erisa_status: 'Unknown',
        quality_score: 91,
        is_low_signal: false,
        fingerprint: 'family-mayo-getting-approval-provenge',
      },
      {
        observation_id: 'family-mayo-petscan-denied',
        canonical_url: 'https://connect.mayoclinic.org/discussion/ins-denied-petscan-all-research-shows-it-sb-done/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Patient asks why insurance denied a PET scan needed for myeloma workup',
        raw_text: 'Mayo Clinic Connect discussion about a PET scan denial during myeloma workup, with comments explaining that plans often deny until a formal diagnosis step is logged.',
        story_excerpt: 'Good because it shows the hidden sequencing rules insurers use for advanced imaging.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'PET scan for myeloma workup',
        procedure_normalized: 'PET scan',
        denial_reason_raw: 'Advanced imaging denied until required diagnostic steps or formal diagnosis are documented',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 87,
        is_low_signal: false,
        fingerprint: 'family-mayo-petscan-denied',
      },
      {
        observation_id: 'family-mayo-cpap-denied',
        canonical_url: 'https://connect.mayoclinic.org/discussion/insurance-wont-cover-cpap/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Patient says insurance would not cover CPAP despite documented sleep disorder',
        raw_text: 'Mayo Clinic Connect discussion about CPAP coverage being denied or delayed even after sleep testing and clinician recommendation.',
        story_excerpt: 'Useful because it captures how device and durable-equipment denials can drag on even when the diagnosis is already clear.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'CPAP coverage',
        procedure_normalized: 'Durable medical equipment',
        denial_reason_raw: 'CPAP denied or delayed despite documented sleep-study results and clinician support',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 86,
        is_low_signal: false,
        fingerprint: 'family-mayo-cpap-denied',
      },
      {
        observation_id: 'family-mayo-specialty-drug-denial',
        canonical_url: 'https://connect.mayoclinic.org/discussion/insurance-denied-my-medication/',
        source_type: 'public_patient_forum',
        source_label: 'Mayo Clinic Connect',
        source_weight: 'public_patient_forum',
        title: 'Patients compare specialty-drug denials and repeated authorization loops',
        raw_text: 'Mayo Clinic Connect thread about insurance denying medication after a drug was already helping, forcing patients back through repeated prior authorization and appeal steps.',
        story_excerpt: 'A strong specialty-medication precedent source because the denial is specific, recurring, and tied to the practical burden of repeated paperwork.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Specialty medication coverage',
        procedure_normalized: 'Prescription medication',
        denial_reason_raw: 'Specialty drug denied after repeat prior authorization or continuation-of-therapy barriers',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-mayo-specialty-drug-denial',
      },
    ],
  },
  {
    id: 'glp1-coverage',
    name: 'GLP-1 and obesity medication coverage fights',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-zepbound-denied',
        canonical_url: 'https://www.reddit.com/r/Zepbound/comments/1gjf264/insurance_denied_zepbound/',
        source_type: 'public_patient_forum',
        source_label: 'Reddit r/Zepbound',
        source_weight: 'public_patient_forum',
        title: 'Insurance denied Zepbound',
        raw_text: 'Patient reporting direct insurance denial of Zepbound and trying to decode prior authorization and exclusion logic.',
        story_excerpt: 'Strong GLP-1 denial signal around obesity medication access.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Zepbound coverage',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'Weight-loss drug denied through plan exclusion or prior authorization',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 91,
        is_low_signal: false,
        fingerprint: 'family-zepbound-denied',
      },
      {
        observation_id: 'family-zepbound-optumrx-appeal',
        canonical_url: 'https://www.reddit.com/r/Zepbound/comments/1i16n2y/insurance_appeals_optumrx/',
        source_type: 'public_patient_forum',
        source_label: 'Reddit r/Zepbound',
        source_weight: 'public_patient_forum',
        title: 'OptumRx appeals over Zepbound coverage',
        raw_text: 'Public discussion focused on OptumRx and appeals over Zepbound coverage denials.',
        story_excerpt: 'High-value because it links a named payer to a named drug and an appeal pathway.',
        insurer_raw: 'OptumRx',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Zepbound coverage and appeal',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'Prior authorization and formulary barriers for Zepbound under OptumRx',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 94,
        is_low_signal: false,
        fingerprint: 'family-zepbound-optumrx-appeal',
      },
      {
        observation_id: 'family-mounjaro-coverage-community',
        canonical_url: 'https://www.reddit.com/r/Mounjaro/',
        source_type: 'public_patient_forum',
        source_label: 'Reddit r/Mounjaro',
        source_weight: 'public_patient_forum',
        title: 'Mounjaro communities documenting repeat coverage denials',
        raw_text: 'Public patient posts in Mounjaro communities repeatedly describe formulary exclusions, step therapy, and abrupt loss of coverage for GLP-1 medication.',
        story_excerpt: 'Another strong GLP-1 lane because the same denial themes keep repeating across plans and payers.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Mounjaro coverage',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'GLP-1 medication blocked through exclusions, step therapy, or prior authorization',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 86,
        is_low_signal: false,
        fingerprint: 'family-mounjaro-coverage-community',
      },
      {
        observation_id: 'family-ozempic-coverage-community',
        canonical_url: 'https://www.reddit.com/r/Ozempic/',
        source_type: 'public_patient_forum',
        source_label: 'Reddit r/Ozempic',
        source_weight: 'public_patient_forum',
        title: 'Ozempic communities documenting coverage denials',
        raw_text: 'The Ozempic community includes repeated stories about step therapy, prior authorization, and abrupt loss of coverage.',
        story_excerpt: 'Broad but valuable evidence that GLP-1 denials are a recurring consumer fight, not a one-off.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Ozempic coverage',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'Step therapy, prior authorization, and plan exclusions for GLP-1 medication',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 86,
        is_low_signal: false,
        fingerprint: 'family-ozempic-coverage-community',
      },
    ],
  },
  {
    id: 'mental-health-parity',
    name: 'Mental health parity and therapy coverage sources',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-dol-parity',
        canonical_url: 'https://www.dol.gov/agencies/ebsa/laws-and-regulations/laws/mental-health-and-substance-use-disorder-parity',
        source_type: 'official_regulatory',
        source_label: 'Department of Labor',
        source_weight: 'official_regulatory',
        title: 'Mental health parity protections define insurer obligations',
        raw_text: 'Department of Labor parity guidance explains that mental health and addiction treatment cannot be more restrictive than comparable medical benefits.',
        story_excerpt: 'Useful legal benchmark for patients fighting therapy and psychiatry denials.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Therapy, psychiatry, and behavioral health care',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Mental health parity violations and restrictive coverage limits',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'ERISA',
        quality_score: 95,
        is_low_signal: false,
        fingerprint: 'family-dol-parity',
      },
      {
        observation_id: 'family-nami-denials-guide',
        canonical_url: 'https://www.nami.org/nami-news/nami-releases-new-guide-to-help-fight-coverage-denials-of-mental-health-addiction-care/',
        source_type: 'official_regulatory',
        source_label: 'NAMI',
        source_weight: 'official_regulatory',
        title: 'NAMI guide to fighting mental health coverage denials',
        raw_text: 'NAMI guidance on fighting mental health and addiction treatment denials, including how patients are forced out of network or denied needed care.',
        story_excerpt: 'High-value because it speaks directly to therapy and psychiatric care denials patients can fight.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Therapy, psychiatry, and addiction treatment',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Mental health treatment denied or pushed out of network',
        denial_category: 'Out of Network',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 92,
        is_low_signal: false,
        fingerprint: 'family-nami-denials-guide',
      },
      {
        observation_id: 'family-autismspeaks-aba-law',
        canonical_url: 'https://www.autismspeaks.org/advocacy-news/autism-speaks-celebrates-new-california-law-protecting-access-behavioral-health',
        source_type: 'official_regulatory',
        source_label: 'Autism Speaks',
        source_weight: 'official_regulatory',
        title: 'Autism coverage fights over repeated re-diagnosis and ABA access',
        raw_text: 'Autism Speaks describes insurer practices that force repeated autism re-diagnoses to keep ABA and behavioral health treatment covered.',
        story_excerpt: 'High-value benchmark for autism families fighting behavioral health denials and repeated re-authorization burdens.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'ABA therapy and behavioral health treatment',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Repeated re-diagnosis requirement and behavioral health access barriers for autism treatment',
        denial_category: 'Prior Authorization',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 93,
        is_low_signal: false,
        fingerprint: 'family-autismspeaks-aba-law',
      },
      {
        observation_id: 'family-autismspeaks-standards-care',
        canonical_url: 'https://www.autismspeaks.org/advocacy-news/importance-generally-accepted-standards-care',
        source_type: 'official_regulatory',
        source_label: 'Autism Speaks',
        source_weight: 'official_regulatory',
        title: 'Autism care denials framed against generally accepted standards of care',
        raw_text: 'Autism Speaks warns that insurers can narrow medically necessary autism benefits by drifting away from generally accepted standards of care.',
        story_excerpt: 'Strong benchmark material for autism denials labeled as not medically necessary or limited by restrictive standards.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Autism behavioral health treatment',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Autism services restricted by insurer interpretation of medical necessity and standards of care',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 91,
        is_low_signal: false,
        fingerprint: 'family-autismspeaks-standards-care',
      },
      {
        observation_id: 'family-mental-health-america-parity',
        canonical_url: 'https://mhanational.org/issues/access-care',
        source_type: 'official_regulatory',
        source_label: 'Mental Health America',
        source_weight: 'official_regulatory',
        title: 'Mental Health America documents access-to-care barriers',
        raw_text: 'Mental Health America explains how insurer restrictions, provider shortages, and parity gaps block access to therapy and psychiatric care.',
        story_excerpt: 'Helpful benchmark source for therapy, psychiatry, and parity-related coverage barriers.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Therapy and psychiatric care',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Mental health care blocked through restrictive coverage or parity failures',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-mental-health-america-parity',
      },
    ],
  },
  {
    id: 'cancer-rare-disease',
    name: 'Cancer and rare-disease support communities',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-bco-share-denial',
        canonical_url: 'https://community.breastcancer.org/en/discussion/880142/share-your-insurance-claims-denial-story',
        source_type: 'public_patient_forum',
        source_label: 'Breastcancer.org Community',
        source_weight: 'public_patient_forum',
        title: 'Breast cancer patients sharing denial stories',
        raw_text: 'Breast cancer community thread explicitly collecting insurance denial stories and treatment access barriers.',
        story_excerpt: 'A direct “patients like me” style source for oncology denials and appeal outcomes.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Cancer treatment and reconstruction-related care',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Coverage denial or repeated treatment-access barrier during cancer care',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 94,
        is_low_signal: false,
        fingerprint: 'family-bco-share-denial',
      },
      {
        observation_id: 'family-bco-mri-not-covered',
        canonical_url: 'https://community.breastcancer.org/en/discussion/727995/insurance-company-will-not-cover-my-mri/p2',
        source_type: 'public_patient_forum',
        source_label: 'Breastcancer.org Community',
        source_weight: 'public_patient_forum',
        title: 'Patients compare insurer refusals to cover breast MRI screening',
        raw_text: 'Breastcancer.org discussion where patients and advocates compare MRI denials, pre-certification failures, and what records help overturn the refusal.',
        story_excerpt: 'High-value because it links a specific imaging denial to the documentation people needed to fight back.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Breast MRI coverage',
        procedure_normalized: 'MRI',
        denial_reason_raw: 'Breast MRI denied because insurer says criteria or medical necessity were not met',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 93,
        is_low_signal: false,
        fingerprint: 'family-bco-mri-not-covered',
      },
      {
        observation_id: 'family-bco-revision-denied-four-times',
        canonical_url: 'https://community.breastcancer.org/en/discussion/885091/insurance-denial',
        source_type: 'public_patient_forum',
        source_label: 'Breastcancer.org Community',
        source_weight: 'public_patient_forum',
        title: 'Patients report reconstruction revision denials repeated multiple times',
        raw_text: 'Breastcancer.org thread describing reconstruction revision care denied repeatedly, including reports of UnitedHealthcare denials and less-than-24-hour appeal rejections.',
        story_excerpt: 'A very strong public precedent source because it names the treatment, the payer behavior, and the failed appeal cycle.',
        insurer_raw: 'United Healthcare',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Breast reconstruction revision care',
        procedure_normalized: 'Breast reconstruction revision care',
        denial_reason_raw: 'Reconstruction revision denied repeatedly despite large physician documentation packets',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 95,
        is_low_signal: false,
        fingerprint: 'family-bco-revision-denied-four-times',
      },
      {
        observation_id: 'family-bco-genetic-testing-story',
        canonical_url: 'https://community.breastcancer.org/en/discussion/comment/4522226',
        source_type: 'public_patient_forum',
        source_label: 'Breastcancer.org Community',
        source_weight: 'public_patient_forum',
        title: 'Genetic testing discussion includes insurance denial and reconstruction coverage confusion',
        raw_text: 'Breastcancer.org discussion around genetic testing and reconstruction includes patient concern about insurance denial, coverage confusion, and appeals tied to diagnosis.',
        story_excerpt: 'Useful because genetic testing and reconstruction fights often turn on narrow policy language and family-risk documentation.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Genetic testing and reconstruction-related care',
        procedure_normalized: 'Genetic testing',
        denial_reason_raw: 'Coverage questioned or denied because insurer disputes criteria for testing or reconstructive treatment',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 84,
        is_low_signal: false,
        fingerprint: 'family-bco-genetic-testing-story',
      },
      {
        observation_id: 'family-bco-reconstruction-coverage',
        canonical_url: 'https://community.breastcancer.org/en/discussion/747304/diep-flap-and-insurance',
        source_type: 'public_patient_forum',
        source_label: 'Breastcancer.org Community',
        source_weight: 'public_patient_forum',
        title: 'Breast reconstruction patients compare insurer fights over DIEP flap coverage',
        raw_text: 'Breastcancer.org discussion on DIEP flap and reconstruction coverage, including repeated insurer pushback and what documentation finally mattered.',
        story_excerpt: 'Useful because reconstruction denials often hinge on narrow policy language and repeated arguments about necessity versus cosmetic labeling.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'DIEP flap reconstruction coverage',
        procedure_normalized: 'Breast reconstruction revision care',
        denial_reason_raw: 'Breast reconstruction delayed or denied through cosmetic labeling or medical-necessity disputes',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 91,
        is_low_signal: false,
        fingerprint: 'family-bco-reconstruction-coverage',
      },
      {
        observation_id: 'family-als-nord-poster',
        canonical_url: 'https://www.als.org/sites/default/files/2024-01/ALS-Focus_2023-NORD-Poster.pdf',
        source_type: 'official_regulatory',
        source_label: 'ALS Association / NORD',
        source_weight: 'official_regulatory',
        title: 'ALS denials and appeal burden survey findings',
        raw_text: 'ALS Association and NORD poster summarizing denials, prior authorization burden, and equipment access barriers in ALS care.',
        story_excerpt: 'Rare high-signal evidence about DME and support denials in ALS.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'ALS care and durable medical equipment',
        procedure_normalized: 'ALS care and durable medical equipment',
        denial_reason_raw: 'Prior authorization denial and equipment access barriers in ALS care',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 95,
        is_low_signal: false,
        fingerprint: 'family-als-nord-poster',
      },
      {
        observation_id: 'family-cancercare-insurance',
        canonical_url: 'https://www.cancercare.org/publications/62-understanding_the_cost_of_care_and_your_health_insurance',
        source_type: 'official_regulatory',
        source_label: 'CancerCare',
        source_weight: 'official_regulatory',
        title: 'Cancer coverage barriers around prior auth and claims',
        raw_text: 'CancerCare guidance on claim denials, prior authorization, and treatment affordability in oncology.',
        story_excerpt: 'Useful benchmark source for cancer patients whose treatment or supportive care gets delayed by coverage fights.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Cancer treatment and oncology supportive care',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Claim denial and authorization friction in cancer care',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 89,
        is_low_signal: false,
        fingerprint: 'family-cancercare-insurance',
      },
      {
        observation_id: 'family-csn-insurance-denied-radiation',
        canonical_url: 'https://csn.cancer.org/discussion/327676/insurance-denied-radiation-treatment',
        source_type: 'public_patient_forum',
        source_label: 'Cancer Survivors Network',
        source_weight: 'public_patient_forum',
        title: 'Cancer Survivors Network discussion on denied radiation treatment',
        raw_text: 'Cancer Survivors Network includes direct patient reports of radiation treatment being denied, delayed, or kicked into appeal despite oncologist support.',
        story_excerpt: 'Higher-fidelity than generic complaint threads because it ties a named treatment type to denial and appeal behavior during active cancer care.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Radiation treatment coverage',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Radiation treatment denied or delayed despite oncology recommendation',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 90,
        is_low_signal: false,
        fingerprint: 'family-csn-insurance-denied-radiation',
      },
      {
        observation_id: 'family-csn-immunotherapy-appeal',
        canonical_url: 'https://csn.cancer.org/discussion/322332/immunotherapy-and-insurance-appeals',
        source_type: 'public_patient_forum',
        source_label: 'Cancer Survivors Network',
        source_weight: 'public_patient_forum',
        title: 'Cancer Survivors Network discussion on immunotherapy and insurance appeals',
        raw_text: 'Cancer patients discuss immunotherapy denials, appeal burdens, and the need to prove medical necessity over and over.',
        story_excerpt: 'Useful because immunotherapy and specialty-drug access denials often produce repeat appeal language we can benchmark.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Immunotherapy coverage',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Specialty cancer treatment denied pending authorization or medical necessity review',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 89,
        is_low_signal: false,
        fingerprint: 'family-csn-immunotherapy-appeal',
      },
      {
        observation_id: 'family-csn-treatment-not-covered',
        canonical_url: 'https://csn.cancer.org/discussion/284502/insurance-wont-pay-for-treatment',
        source_type: 'public_patient_forum',
        source_label: 'Cancer Survivors Network',
        source_weight: 'public_patient_forum',
        title: 'Cancer patient says insurance would not pay for chemo right before start date',
        raw_text: 'Cancer Survivors Network thread where a patient says chemo was scheduled and then the day before treatment they were told the insurance would not cover it.',
        story_excerpt: 'A very clear example of active cancer treatment being blocked at the last minute by coverage decisions.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Chemotherapy coverage',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Chemo denied on the eve of treatment and patient told to challenge coding or appeal',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 91,
        is_low_signal: false,
        fingerprint: 'family-csn-treatment-not-covered',
      },
      {
        observation_id: 'family-csn-breast-disease-exclusion',
        canonical_url: 'https://csn.cancer.org/discussion/136724/insurance-woes',
        source_type: 'public_patient_forum',
        source_label: 'Cancer Survivors Network',
        source_weight: 'public_patient_forum',
        title: 'Patient describes insurer trying to carve out all breast disease after denial',
        raw_text: 'Cancer Survivors Network thread describing a denial letter that came with a waiver attempting to exclude all future breast disease claims, followed by multiple appeal stages.',
        story_excerpt: 'Exceptionally useful because it shows how aggressive exclusion language can become in cancer-related disputes.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Breast disease treatment coverage',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Coverage denied and insurer attempted to exclude future breast-disease claims entirely',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 93,
        is_low_signal: false,
        fingerprint: 'family-csn-breast-disease-exclusion',
      },
      {
        observation_id: 'family-csn-avastin-bcbs',
        canonical_url: 'https://csn.cancer.org/discussion/168932/insurance',
        source_type: 'public_patient_forum',
        source_label: 'Cancer Survivors Network',
        source_weight: 'public_patient_forum',
        title: 'Anthem Blue Cross refused to pay for Avastin until outside appeal',
        raw_text: 'Cancer Survivors Network thread describing Anthem Blue Cross refusing to pay for Avastin chemotherapy for months until the family appealed through the retirement system.',
        story_excerpt: 'Strong precedent source because it names the payer, drug, delay, and the external path that finally worked.',
        insurer_raw: 'Anthem Blue Cross',
        insurer_normalized: 'Blue Cross Blue Shield',
        procedure_raw: 'Avastin chemotherapy coverage',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Chemo denied for months until external appeal outside the carrier process succeeded',
        denial_category: 'Medical Necessity',
        plan_type: 'Employer Sponsored',
        erisa_status: 'ERISA',
        quality_score: 94,
        is_low_signal: false,
        fingerprint: 'family-csn-avastin-bcbs',
      },
      {
        observation_id: 'family-csn-pet-scan-denied',
        canonical_url: 'https://csn.cancer.org/discussion/239777/pet-scan-denied',
        source_type: 'public_patient_forum',
        source_label: 'Cancer Survivors Network',
        source_weight: 'public_patient_forum',
        title: 'Cancer patient says PET scan was denied while treatment planning stalled',
        raw_text: 'Cancer Survivors Network discussion where a patient reports a PET scan denial and tries to figure out how to keep staging and treatment planning moving.',
        story_excerpt: 'Helpful because it ties high-stakes cancer imaging to the same medical-necessity and prior-approval barriers we see elsewhere.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'PET scan for cancer staging',
        procedure_normalized: 'PET scan',
        denial_reason_raw: 'PET scan denied pending further proof of necessity or authorization',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-csn-pet-scan-denied',
      },
      {
        observation_id: 'family-myeloma-beacon-regimen-denial',
        canonical_url: 'https://myelomabeacon.org/forum/insurance-denying-velcade-revlimid-dexamethasone-t3239.html',
        source_type: 'public_patient_forum',
        source_label: 'Myeloma Beacon Forum',
        source_weight: 'public_patient_forum',
        title: 'Myeloma patients describe denial of Velcade, Revlimid, and dexamethasone treatment',
        raw_text: 'Myeloma Beacon forum discussion about insurance denying a Velcade, Revlimid, and dexamethasone regimen and the stress of keeping cancer treatment moving.',
        story_excerpt: 'Strong because it names the disease, the treatment regimen, and the denial fight in one place.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'Velcade Revlimid dexamethasone regimen',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Cancer treatment regimen denied or restricted despite physician treatment plan',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 90,
        is_low_signal: false,
        fingerprint: 'family-myeloma-beacon-regimen-denial',
      },
      {
        observation_id: 'family-myeloma-beacon-revlimid-medicare',
        canonical_url: 'https://myelomabeacon.org/forum/medicare-coverage-of-revlimid-t814-30.html',
        source_type: 'public_patient_forum',
        source_label: 'Myeloma Beacon Forum',
        source_weight: 'public_patient_forum',
        title: 'Myeloma patients compare Medicare coverage barriers for Revlimid',
        raw_text: 'Myeloma Beacon discussion about Medicare Part D coverage of Revlimid, catastrophic out-of-pocket spikes, and what coverage actually looks like for oral cancer drugs.',
        story_excerpt: 'Useful because it ties a named cancer drug to a named plan type and real affordability barriers.',
        insurer_raw: 'Medicare Part D',
        insurer_normalized: 'Medicare',
        procedure_raw: 'Revlimid medication coverage',
        procedure_normalized: 'Cancer treatment and oncology care',
        denial_reason_raw: 'Coverage restrictions and extreme out-of-pocket burden around oral oncology drug coverage under Medicare Part D',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Medicare Part D',
        erisa_status: 'Non-ERISA',
        quality_score: 87,
        is_low_signal: false,
        fingerprint: 'family-myeloma-beacon-revlimid-medicare',
      },
      {
        observation_id: 'family-myeloma-beacon-scan-denial',
        canonical_url: 'https://myelomabeacon.org/forum/pet-scan-insurance-denial-t4981.html',
        source_type: 'public_patient_forum',
        source_label: 'Myeloma Beacon Forum',
        source_weight: 'public_patient_forum',
        title: 'Myeloma patients compare PET scan denial fights and insurer sequencing rules',
        raw_text: 'Myeloma Beacon discussion about PET scan insurance denials and how plans force patients through additional diagnostic steps before covering imaging.',
        story_excerpt: 'A good fit for our record because it captures repeat imaging barriers in a high-cost oncology context.',
        insurer_raw: 'Unknown',
        insurer_normalized: 'Unknown',
        procedure_raw: 'PET scan coverage',
        procedure_normalized: 'PET scan',
        denial_reason_raw: 'PET scan denied because insurer required extra diagnostic proof before approving imaging',
        denial_category: 'Prior Authorization',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 86,
        is_low_signal: false,
        fingerprint: 'family-myeloma-beacon-scan-denial',
      },
      {
        observation_id: 'family-healthboards-anthem-oats',
        canonical_url: 'https://www.healthboards.com/boards/foot-ankle-problems/771661-anthem-denies-oats-daughter-now-what.html',
        source_type: 'public_patient_forum',
        source_label: 'HealthBoards',
        source_weight: 'public_patient_forum',
        title: 'Anthem denial of OATS surgery leaves family searching for next steps',
        raw_text: 'HealthBoards discussion about Anthem denying OATS surgery and a family scrambling for appeal options after the rejection.',
        story_excerpt: 'Useful because it names both the payer and the denied surgery instead of just describing generic insurance frustration.',
        insurer_raw: 'Anthem',
        insurer_normalized: 'Blue Cross Blue Shield',
        procedure_raw: 'OATS surgery',
        procedure_normalized: 'Surgery',
        denial_reason_raw: 'Orthopedic surgery denied and family forced to search for appeal or alternate options',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 88,
        is_low_signal: false,
        fingerprint: 'family-healthboards-anthem-oats',
      },
      {
        observation_id: 'family-alz-healthcare-appeals',
        canonical_url: 'https://www.alz.org/Help-Support/Caregiving/Financial-Legal-Planning/Healthcare-Appeals-for-People-with-Alzheimers-and',
        source_type: 'official_regulatory',
        source_label: "Alzheimer's Association",
        source_weight: 'official_regulatory',
        title: 'Health care appeals for people with Alzheimer’s and other dementias',
        raw_text: 'The Alzheimer’s Association explains how caregivers can appeal denials when dementia-related services, treatment, or medication are refused as not medically necessary or too frequent.',
        story_excerpt: 'Strong benchmark material for dementia-care denials and caregiver appeal strategy.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Dementia care services and medication coverage',
        procedure_normalized: 'Dementia care and medication coverage',
        denial_reason_raw: 'Dementia-related treatment or medication denied as not medically necessary or too frequent',
        denial_category: 'Medical Necessity',
        plan_type: 'Medicare',
        erisa_status: 'Non-ERISA',
        quality_score: 94,
        is_low_signal: false,
        fingerprint: 'family-alz-healthcare-appeals',
      },
      {
        observation_id: 'family-alz-medicare-refuses-pay',
        canonical_url: 'https://www.alz.org/media/documents/alzheimers-dementia-medicare-refuse-to-pay-ts.pdf',
        source_type: 'official_regulatory',
        source_label: "Alzheimer's Association",
        source_weight: 'official_regulatory',
        title: 'What to do if Medicare refuses to pay in dementia care',
        raw_text: 'Alzheimer’s Association guidance for caregivers facing Medicare refusals to pay for medical services or procedures tied to dementia care.',
        story_excerpt: 'Useful because it translates denial notices into concrete appeal steps for dementia-related care.',
        insurer_raw: 'Medicare',
        insurer_normalized: 'Medicare',
        procedure_raw: 'Medical service or procedure related to dementia care',
        procedure_normalized: 'Dementia care and medication coverage',
        denial_reason_raw: 'Medicare refuses to pay for service or procedure and caregiver must appeal',
        denial_category: 'Administrative',
        plan_type: 'Medicare',
        erisa_status: 'Non-ERISA',
        quality_score: 92,
        is_low_signal: false,
        fingerprint: 'family-alz-medicare-refuses-pay',
      },
    ],
  },
  {
    id: 'court-lawsuits',
    name: 'Court and lawsuit intelligence',
    strategy: 'automated',
    observations: [
      {
        observation_id: 'family-stat-navihealth-lawsuit',
        canonical_url: 'https://www.statnews.com/2023/11/14/unitedhealth-navihealth-lawsuit-medicare-advantage/',
        source_type: 'investigative',
        source_label: 'STAT',
        source_weight: 'investigative',
        title: 'UnitedHealth / NaviHealth lawsuit over Medicare Advantage denials',
        raw_text: 'Investigative reporting on lawsuits claiming algorithmic post-acute care denials and premature cutoffs under Medicare Advantage.',
        story_excerpt: 'High-value systemic evidence tying a named insurer to repeat denial tactics and litigation.',
        insurer_raw: 'UnitedHealth / NaviHealth',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Post-acute and skilled nursing coverage',
        procedure_normalized: 'Post-acute care coverage',
        denial_reason_raw: 'Algorithmic or accelerated denial of post-acute care under Medicare Advantage',
        denial_category: 'Medical Necessity',
        plan_type: 'Medicare Advantage',
        erisa_status: 'Non-ERISA',
        quality_score: 96,
        is_low_signal: false,
        fingerprint: 'family-stat-navihealth-lawsuit',
      },
      {
        observation_id: 'family-courtlistener-search-united',
        canonical_url: 'https://www.courtlistener.com/help/search-operators/',
        source_type: 'investigative',
        source_label: 'CourtListener / legal search',
        source_weight: 'investigative',
        title: 'CourtListener can be used to monitor insurer denial litigation',
        raw_text: 'CourtListener search and API infrastructure make it possible to monitor lawsuits and docket activity around prior authorization, parity, and insurer denials.',
        story_excerpt: 'Not a patient story, but a high-value legal intelligence source for repeated insurer tactics and class-action risk.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Denial-related litigation and dockets',
        procedure_normalized: 'Denial-related litigation',
        denial_reason_raw: 'Litigation alleging insurer denial tactics or parity violations',
        denial_category: 'Administrative',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 82,
        is_low_signal: false,
        fingerprint: 'family-courtlistener-search-united',
      },
      {
        observation_id: 'family-propublica-autism-treatment',
        canonical_url: 'https://www.propublica.org/article/unitedhealth-strategically-limiting-autism-treatment',
        source_type: 'investigative',
        source_label: 'ProPublica',
        source_weight: 'investigative',
        title: 'Investigative reporting on autism-treatment limits',
        raw_text: 'Investigative reporting on how a major insurer limited autism treatment, creating a strong public-interest record around repeat behavioral-health denials.',
        story_excerpt: 'High-value precedent material because it connects a named insurer, a named treatment area, and a broader denial pattern.',
        insurer_raw: 'UnitedHealthcare',
        insurer_normalized: 'UnitedHealthcare',
        procedure_raw: 'Autism treatment and ABA therapy',
        procedure_normalized: 'ABA therapy',
        denial_reason_raw: 'Behavioral-health treatment restricted through internal insurer limits',
        denial_category: 'Medical Necessity',
        plan_type: 'Commercial',
        erisa_status: 'Unknown',
        quality_score: 95,
        is_low_signal: false,
        fingerprint: 'family-propublica-autism-treatment',
      },
    ],
  },
  {
    id: 'public-facebook-discovery',
    name: 'Public Facebook discovery lane',
    strategy: 'manual_review',
    observations: [
      {
        observation_id: 'family-facebook-oac-public',
        canonical_url: 'https://www.facebook.com/obesityaction/',
        source_type: 'social_chatter',
        source_label: 'Facebook public advocacy page',
        source_weight: 'social_chatter',
        title: 'Public social discussion around obesity coverage barriers',
        raw_text: 'Public advocacy-page discussions can surface GLP-1 and obesity-treatment coverage complaints, but they require manual review before promotion.',
        story_excerpt: 'This lane is for discovery only until we have cleaner public-post harvesting rules.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'GLP-1 medication and obesity treatment',
        procedure_normalized: 'GLP-1 medication',
        denial_reason_raw: 'Public social discussion about coverage denial or exclusion',
        denial_category: 'Coverage Exclusion',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 60,
        is_low_signal: false,
        fingerprint: 'family-facebook-oac-public',
      },
      {
        observation_id: 'family-facebook-nami-public',
        canonical_url: 'https://www.facebook.com/NAMI/',
        source_type: 'social_chatter',
        source_label: 'Facebook public advocacy page',
        source_weight: 'social_chatter',
        title: 'Public social discussion around mental health coverage denials',
        raw_text: 'Public advocacy-page discussions can surface therapy and psychiatry coverage barriers, but they should stay in a manual-review lane unless a post is clearly public and denial-specific.',
        story_excerpt: 'A cautious public-social lane for discovery, not blind promotion.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'Therapy services and psychiatric care',
        procedure_normalized: 'Therapy services',
        denial_reason_raw: 'Mental health coverage denied or restricted',
        denial_category: 'Out of Network',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 58,
        is_low_signal: false,
        fingerprint: 'family-facebook-nami-public',
      },
      {
        observation_id: 'family-facebook-autismspeaks-public',
        canonical_url: 'https://www.facebook.com/autismspeaks/',
        source_type: 'social_chatter',
        source_label: 'Facebook public advocacy page',
        source_weight: 'social_chatter',
        title: 'Public social discussion around autism-treatment coverage',
        raw_text: 'Public advocacy-page discussions can surface ABA therapy and autism-treatment coverage barriers, but this lane stays in manual review unless the post is clearly public and denial-specific.',
        story_excerpt: 'Discovery lane for autism-treatment complaints on clearly public advocacy pages.',
        insurer_raw: 'Multiple insurers',
        insurer_normalized: 'Multiple insurers',
        procedure_raw: 'ABA therapy and autism-treatment coverage',
        procedure_normalized: 'ABA therapy',
        denial_reason_raw: 'Public social discussion about autism-treatment denials or insurer limits',
        denial_category: 'Medical Necessity',
        plan_type: 'Unknown',
        erisa_status: 'Unknown',
        quality_score: 58,
        is_low_signal: false,
        fingerprint: 'family-facebook-autismspeaks-public',
      },
    ],
  },
];

export const SOURCE_FAMILY_OBSERVATIONS: TrustedObservation[] = SOURCE_FAMILY_PACKS.flatMap((family) => family.observations);
