export type TrustedObservation = {
  observation_id: string;
  canonical_url: string;
  source_type: string;
  source_label: string;
  source_weight: string;
  title: string;
  raw_text: string;
  story_excerpt: string;
  insurer_raw: string;
  insurer_normalized: string;
  procedure_raw: string;
  procedure_normalized: string;
  denial_reason_raw: string;
  denial_category: string;
  plan_type: string;
  erisa_status: string;
  quality_score: number;
  is_low_signal: boolean;
  fingerprint: string;
};

export const TRUSTED_OBSERVATION_PACK: TrustedObservation[] = [
  {
    observation_id: 'trusted-aarp-uhc-appeals',
    canonical_url: 'https://community.aarp.org/t5/Medicare-Insurance/United-Healthcare/m-p/2604984',
    source_type: 'public_patient_forum',
    source_label: 'AARP Medicare Insurance Forum',
    source_weight: 'public_patient_forum',
    title: 'Older patients describing UnitedHealthcare delay and denial pressure',
    raw_text: 'AARP Medicare forum discussion about UnitedHealthcare delay, denial pressure, and appeal frustration inside Medicare managed care.',
    story_excerpt: 'Older adults describing denial delays and the feeling that appeals are stacked against them.',
    insurer_raw: 'United Healthcare',
    insurer_normalized: 'UnitedHealthcare',
    procedure_raw: 'Medicare treatment authorization',
    procedure_normalized: 'Medicare treatment authorization',
    denial_reason_raw: 'Delay, authorization friction, and denial pressure under managed care review',
    denial_category: 'Prior Authorization',
    plan_type: 'Medicare Advantage',
    erisa_status: 'Non-ERISA',
    quality_score: 84,
    is_low_signal: false,
    fingerprint: 'trusted-aarp-uhc-appeals',
  },
  {
    observation_id: 'trusted-bco-reconstruction-denial',
    canonical_url: 'https://community.breastcancer.org/en/discussion/885091/insurance-denial',
    source_type: 'public_patient_forum',
    source_label: 'Breastcancer.org Community',
    source_weight: 'public_patient_forum',
    title: 'Repeated denial of breast reconstruction revision care',
    raw_text: 'Public patient discussion about repeated denial of reconstruction revision care despite documentation and fast failed appeals.',
    story_excerpt: 'A strong patient narrative around repeated insurer denials in reconstruction care.',
    insurer_raw: 'United Healthcare',
    insurer_normalized: 'UnitedHealthcare',
    procedure_raw: 'Breast reconstruction revision care',
    procedure_normalized: 'Breast reconstruction revision care',
    denial_reason_raw: 'Reconstruction revision denied repeatedly despite clinical documentation',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 92,
    is_low_signal: false,
    fingerprint: 'trusted-bco-reconstruction-denial',
  },
  {
    observation_id: 'trusted-bbb-uhc-admin',
    canonical_url: 'https://www.bbb.org/us/mn/minnetonka/profile/health-insurance/unitedhealth-group-0704-21000358/complaints',
    source_type: 'complaint_platform',
    source_label: 'BBB Complaints',
    source_weight: 'complaint_platform',
    title: 'UnitedHealth complaint patterns around claims and delays',
    raw_text: 'BBB complaint pages show recurring narratives about denied claims, administrative delays, and lack of insurer response.',
    story_excerpt: 'Administrative failure patterns around claims handling and response timelines.',
    insurer_raw: 'UnitedHealth Group',
    insurer_normalized: 'UnitedHealthcare',
    procedure_raw: 'Claims processing disputes',
    procedure_normalized: 'Claims processing disputes',
    denial_reason_raw: 'Denied claims, delay, and insufficient response',
    denial_category: 'Administrative',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 78,
    is_low_signal: false,
    fingerprint: 'trusted-bbb-uhc-admin',
  },
  {
    observation_id: 'trusted-consumeraffairs-cigna',
    canonical_url: 'https://www.consumeraffairs.com/insurance/cigna_health.html',
    source_type: 'complaint_platform',
    source_label: 'ConsumerAffairs',
    source_weight: 'complaint_platform',
    title: 'Cigna complaint patterns on ConsumerAffairs',
    raw_text: 'ConsumerAffairs complaint aggregation showing recurring patient frustration with coverage denials, prescriptions, and administrative handling by Cigna.',
    story_excerpt: 'Complaint-platform evidence of repeat friction around claims, drugs, and insurer handling.',
    insurer_raw: 'Cigna',
    insurer_normalized: 'Cigna',
    procedure_raw: 'Prescription medication and claims disputes',
    procedure_normalized: 'Prescription medication',
    denial_reason_raw: 'Coverage denial and administrative claim handling problems',
    denial_category: 'Administrative',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 76,
    is_low_signal: false,
    fingerprint: 'trusted-consumeraffairs-cigna',
  },
  {
    observation_id: 'trusted-oig-ma-wrongful-denials',
    canonical_url: 'https://oig.hhs.gov/reports/all/2022/some-medicare-advantage-organization-denials-of-prior-authorization-requests-raise-concerns-about-beneficiary-access-to-care/',
    source_type: 'official_regulatory',
    source_label: 'HHS OIG',
    source_weight: 'official_regulatory',
    title: 'Medicare Advantage denials that should not have happened',
    raw_text: 'HHS OIG found Medicare Advantage organizations denied prior authorization and payment requests that met Medicare coverage rules.',
    story_excerpt: 'One of the strongest official benchmark sources for wrongful denial patterns in Medicare Advantage.',
    insurer_raw: 'Medicare Advantage organizations',
    insurer_normalized: 'Medicare Advantage organizations',
    procedure_raw: 'Prior authorization requests and payment decisions',
    procedure_normalized: 'Prior authorization requests and payment decisions',
    denial_reason_raw: 'Coverage denials on requests that met Medicare rules',
    denial_category: 'Medical Necessity',
    plan_type: 'Medicare Advantage',
    erisa_status: 'Non-ERISA',
    quality_score: 96,
    is_low_signal: false,
    fingerprint: 'trusted-oig-ma-wrongful-denials',
  },
  {
    observation_id: 'trusted-kff-marketplace-denials',
    canonical_url: 'https://www.kff.org/private-insurance/issue-brief/claims-denials-and-appeals-in-aca-marketplace-plans/',
    source_type: 'official_regulatory',
    source_label: 'KFF',
    source_weight: 'official_regulatory',
    title: 'Marketplace claims denials and low appeal rates',
    raw_text: 'KFF analysis of marketplace plan disclosures showing meaningful denial rates and very low appeal use.',
    story_excerpt: 'A benchmark source for just how many people never appeal after denial.',
    insurer_raw: 'ACA marketplace insurers',
    insurer_normalized: 'ACA marketplace insurers',
    procedure_raw: 'Marketplace claims',
    procedure_normalized: 'Marketplace claims',
    denial_reason_raw: 'Claim denial rates and low appeal uptake',
    denial_category: 'Administrative',
    plan_type: 'Marketplace',
    erisa_status: 'Non-ERISA',
    quality_score: 91,
    is_low_signal: false,
    fingerprint: 'trusted-kff-marketplace-denials',
  },
  {
    observation_id: 'trusted-obesity-glp1-access',
    canonical_url: 'https://www.obesityaction.org/action-through-advocacy/access-to-care/access-to-obesity-care-and-treatments/',
    source_type: 'official_regulatory',
    source_label: 'Obesity Action Coalition',
    source_weight: 'official_regulatory',
    title: 'Coverage fights over obesity treatment and GLP-1 medications',
    raw_text: 'Obesity Action Coalition resource focused on exclusions, prior authorization barriers, and access problems for obesity care and anti-obesity medication.',
    story_excerpt: 'A strong benchmark source for GLP-1 coverage fights and exclusions.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Obesity care and anti-obesity medication coverage',
    procedure_normalized: 'GLP-1 medication',
    denial_reason_raw: 'Coverage exclusion and prior authorization barriers for obesity treatment',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 91,
    is_low_signal: false,
    fingerprint: 'trusted-obesity-glp1-access',
  },
  {
    observation_id: 'trusted-cancercare-oncology-auth',
    canonical_url: 'https://www.cancercare.org/publications/62-understanding_the_cost_of_care_and_your_health_insurance',
    source_type: 'official_regulatory',
    source_label: 'CancerCare',
    source_weight: 'official_regulatory',
    title: 'Oncology coverage barriers and prior authorization friction',
    raw_text: 'CancerCare guidance on treatment costs, prior authorization barriers, claim denials, and insurance navigation in cancer care.',
    story_excerpt: 'A benchmark source for oncology access, denials, and financial toxicity.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Cancer treatment and oncology supportive care',
    procedure_normalized: 'Cancer treatment and oncology care',
    denial_reason_raw: 'Coverage barriers and prior authorization friction in cancer care',
    denial_category: 'Prior Authorization',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 89,
    is_low_signal: false,
    fingerprint: 'trusted-cancercare-oncology-auth',
  },
  {
    observation_id: 'trusted-autism-aba-denial',
    canonical_url: 'https://www.autismspeaks.org/tool-kit-excerpt/what-if-my-insurance-company-denies-coverage',
    source_type: 'official_regulatory',
    source_label: 'Autism Speaks',
    source_weight: 'official_regulatory',
    title: 'Families dealing with autism therapy denials',
    raw_text: 'Autism Speaks guidance for families facing coverage denials for autism-related services and ABA therapy.',
    story_excerpt: 'A high-value source for ABA coverage fights, mandate navigation, and family appeals.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Autism therapy and ABA coverage',
    procedure_normalized: 'Autism therapy',
    denial_reason_raw: 'Autism service denial and coverage disputes',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 92,
    is_low_signal: false,
    fingerprint: 'trusted-autism-aba-denial',
  },
  {
    observation_id: 'trusted-nami-mental-health-insurance',
    canonical_url: 'https://www.nami.org/Your-Journey/Individuals-with-Mental-Illness/Getting-Mental-Health-Support/Understanding-Health-Insurance',
    source_type: 'official_regulatory',
    source_label: 'NAMI',
    source_weight: 'official_regulatory',
    title: 'Mental health coverage barriers for therapy and psychiatry',
    raw_text: 'NAMI overview of mental health coverage, in-network versus out-of-network access, appeals, and behavioral-health benefits.',
    story_excerpt: 'A benchmark source for depression, anxiety, therapy, psychiatry, and behavioral-health access problems.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Therapy services and psychiatric care',
    procedure_normalized: 'Therapy services',
    denial_reason_raw: 'Mental health coverage limitation or access dispute',
    denial_category: 'Out of Network',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 89,
    is_low_signal: false,
    fingerprint: 'trusted-nami-mental-health-insurance',
  },
  {
    observation_id: 'trusted-als-benefits-guide',
    canonical_url: 'https://www.als.org/order-portal/resource-guide/understanding-insurance-and-benefits-when-you-have-als',
    source_type: 'official_regulatory',
    source_label: 'The ALS Association',
    source_weight: 'official_regulatory',
    title: 'ALS benefits navigation and coverage barriers',
    raw_text: 'ALS Association guidance covering private insurance, Medicare, Medicaid, disability, and equipment/support benefit navigation for people with ALS.',
    story_excerpt: 'Useful for high-cost disease coverage barriers around equipment, home care, and respiratory support.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'ALS care, DME, respiratory and home support coverage',
    procedure_normalized: 'ALS care and durable medical equipment',
    denial_reason_raw: 'Coverage barriers, benefit limitations, and appeal support needs',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 89,
    is_low_signal: false,
    fingerprint: 'trusted-als-benefits-guide',
  },
  {
    observation_id: 'trusted-alz-dementia-insurance',
    canonical_url: 'https://www.alz.org/Help-Support/Caregiving/Financial-Legal-Planning/Insurance',
    source_type: 'official_regulatory',
    source_label: "Alzheimer's Association",
    source_weight: 'official_regulatory',
    title: 'Dementia care and long-term support coverage barriers',
    raw_text: 'Alzheimer’s Association resource on Medicare, Medicaid, long-term care insurance, and private coverage for dementia care.',
    story_excerpt: 'A benchmark source for long-term dementia support and caregiver financial strain.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Dementia care and long-term support',
    procedure_normalized: 'Dementia care and long-term support',
    denial_reason_raw: 'Coverage limitations for long-term dementia care',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 87,
    is_low_signal: false,
    fingerprint: 'trusted-alz-dementia-insurance',
  },
  {
    observation_id: 'trusted-crohns-denied-coverage',
    canonical_url: 'https://www.crohnscolitisfoundation.org/managing-the-cost-of-ibd/what-to-do-if-denied-coverage',
    source_type: 'official_regulatory',
    source_label: "Crohn's & Colitis Foundation",
    source_weight: 'official_regulatory',
    title: 'IBD medication and treatment denials forcing urgent appeals',
    raw_text: 'Crohn’s & Colitis Foundation guidance focused on denied coverage for medication, treatment, and service access for people with IBD, including short appeal deadlines and sample appeal letters.',
    story_excerpt: 'A high-signal source for biologic denials, treatment interruption, and urgent IBD appeals.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'IBD treatment and biologic medication coverage',
    procedure_normalized: 'Infusion therapy',
    denial_reason_raw: 'Denied coverage for medication, treatment, or service requiring appeal before a short deadline',
    denial_category: 'Prior Authorization',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 93,
    is_low_signal: false,
    fingerprint: 'trusted-crohns-denied-coverage',
  },
  {
    observation_id: 'trusted-asan-autism-coverage',
    canonical_url: 'https://autisticadvocacy.org/policy/toolkits/healthcoverage/',
    source_type: 'official_regulatory',
    source_label: 'Autistic Self Advocacy Network',
    source_weight: 'official_regulatory',
    title: 'Autism-related services coverage varies sharply by plan type',
    raw_text: 'ASAN coverage resources explain how private insurance, Medicaid, and other coverage sources handle autism-related services differently, including fights over ABA and medically necessary interventions.',
    story_excerpt: 'Useful for separating plan-type issues from insurer behavior in autism service denials.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Autism-related services and ABA coverage',
    procedure_normalized: 'Autism therapy',
    denial_reason_raw: 'Coverage disputes over autism-related services and behavior-based treatment',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 91,
    is_low_signal: false,
    fingerprint: 'trusted-asan-autism-coverage',
  },
  {
    observation_id: 'trusted-chadd-adhd-insurance-survey',
    canonical_url: 'https://chadd.org/wp-content/uploads/2018/06/CHADD-Health-Insurance-Survey-Preliminary-Findings.pdf',
    source_type: 'official_regulatory',
    source_label: 'CHADD',
    source_weight: 'official_regulatory',
    title: 'ADHD patients report medication and provider coverage gaps',
    raw_text: 'CHADD survey findings on ADHD health insurance coverage gaps, including non-coverage of preferred medications and difficulties accessing care through insurance.',
    story_excerpt: 'A strong ADHD and psychiatric medication signal around preferred-drug denials and inadequate coverage.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'ADHD medication and psychiatric care',
    procedure_normalized: 'Prescription medication',
    denial_reason_raw: 'Preferred medication not covered and provider access constrained by insurance',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 86,
    is_low_signal: false,
    fingerprint: 'trusted-chadd-adhd-insurance-survey',
  },
  {
    observation_id: 'trusted-nami-coverage-denials-guide',
    canonical_url: 'https://www.nami.org/nami-news/nami-releases-new-guide-to-help-fight-coverage-denials-of-mental-health-addiction-care/',
    source_type: 'official_regulatory',
    source_label: 'NAMI',
    source_weight: 'official_regulatory',
    title: 'Mental health and addiction care denials force out-of-network care',
    raw_text: 'NAMI guide on fighting coverage denials of mental health and addiction care, including parity rights, administrative appeals, and the ways patients are pushed out of network.',
    story_excerpt: 'A high-value source for depression, anxiety, therapy, psychiatry, and behavioral health denial patterns.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Therapy, psychiatry, and addiction treatment',
    procedure_normalized: 'Therapy services',
    denial_reason_raw: 'Mental health or addiction treatment denied, restricted, or pushed out of network',
    denial_category: 'Out of Network',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 92,
    is_low_signal: false,
    fingerprint: 'trusted-nami-coverage-denials-guide',
  },
  {
    observation_id: 'trusted-als-denials-survey',
    canonical_url: 'https://www.als.org/sites/default/files/2024-01/ALS-Focus_2023-NORD-Poster.pdf',
    source_type: 'official_regulatory',
    source_label: 'ALS Association / NORD',
    source_weight: 'official_regulatory',
    title: 'ALS prior authorization denials and appeal burden are common',
    raw_text: 'ALS Association and NORD poster summarizing insurance denials and appeals experiences in ALS care, including prior authorization denials, durable medical equipment, and caregiver support.',
    story_excerpt: 'A rare high-signal source on ALS denials, equipment access, and appeal burden.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'ALS care, prior authorization, and durable medical equipment',
    procedure_normalized: 'ALS care and durable medical equipment',
    denial_reason_raw: 'Prior authorization denial and equipment access barriers in ALS care',
    denial_category: 'Prior Authorization',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 95,
    is_low_signal: false,
    fingerprint: 'trusted-als-denials-survey',
  },
];
