import { getBigQueryAccessToken } from './_bigqueryClient';

const DATASET_ID = process.env.BIGQUERY_DATASET_ID || 'fight_insurance_denials';
const TABLE_ID = 'raw_web_observations';

const observations = [
  {
    observation_id: 'aarp-uhc-appeals-001',
    canonical_url: 'https://community.aarp.org/t5/Medicare-Insurance/United-Healthcare/m-p/2604984',
    source_type: 'public_patient_forum',
    source_label: 'AARP Medicare Insurance Forum',
    source_weight: 'public_patient_forum',
    title: 'United Healthcare discussion and appeal frustration',
    raw_text: 'AARP Medicare Insurance forum thread discussing United Healthcare delays, denials, and appeal frustration in Medicare managed care.',
    story_excerpt: 'Public older-adult community discussion about delay, denial, and appeal dynamics with United Healthcare.',
    insurer_raw: 'United Healthcare',
    insurer_normalized: 'UnitedHealthcare',
    procedure_raw: 'Medicare treatment authorization',
    procedure_normalized: 'Medicare treatment authorization',
    denial_reason_raw: 'Delay and denial of care under managed care review',
    denial_category: 'Prior Authorization',
    plan_type: 'Medicare Advantage',
    erisa_status: 'Non-ERISA',
    quality_score: 82,
    is_low_signal: false,
    fingerprint: 'aarp-uhc-appeals-001',
  },
  {
    observation_id: 'aarp-policy-change-004',
    canonical_url: 'https://community.aarp.org/t5/Medicare-Insurance/Two-Medicare-Policies-Should-be-Changed/m-p/2327332',
    source_type: 'public_patient_forum',
    source_label: 'AARP Medicare Insurance Forum',
    source_weight: 'public_patient_forum',
    title: 'Two Medicare policies should be changed',
    raw_text: 'AARP discussion arguing prior authorization of drugs should not create patient-insurer conflict and delay.',
    story_excerpt: 'Patient frustration signal around drug access and authorization policy.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Drug prior authorization',
    procedure_normalized: 'Drug prior authorization',
    denial_reason_raw: 'Prior authorization burden',
    denial_category: 'Prior Authorization',
    plan_type: 'Medicare Advantage',
    erisa_status: 'Non-ERISA',
    quality_score: 74,
    is_low_signal: false,
    fingerprint: 'aarp-policy-change-004',
  },
  {
    observation_id: 'bco-share-story-001',
    canonical_url: 'https://community.breastcancer.org/en/discussion/880142/share-your-insurance-claims-denial-story',
    source_type: 'public_patient_forum',
    source_label: 'Breastcancer.org Community',
    source_weight: 'public_patient_forum',
    title: 'Share your insurance claims denial story',
    raw_text: 'Breastcancer.org community thread explicitly collecting health insurance denial stories tied to treatment or surgery recommendations.',
    story_excerpt: 'High-signal patient narrative collection point focused on real treatment denials.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Breast cancer treatment or surgery',
    procedure_normalized: 'Breast cancer treatment and surgery',
    denial_reason_raw: 'Treatment or surgery denial',
    denial_category: 'Medical Necessity',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 88,
    is_low_signal: false,
    fingerprint: 'bco-share-story-001',
  },
  {
    observation_id: 'bco-insurance-denial-002',
    canonical_url: 'https://community.breastcancer.org/en/discussion/885091/insurance-denial',
    source_type: 'public_patient_forum',
    source_label: 'Breastcancer.org Community',
    source_weight: 'public_patient_forum',
    title: 'Insurance denial discussion',
    raw_text: 'Breastcancer.org discussion about repeated denial of reconstruction revision care and very fast appeal denials despite extensive documentation.',
    story_excerpt: 'Strong signal of repeated insurer denials in reconstruction care.',
    insurer_raw: 'United Healthcare',
    insurer_normalized: 'UnitedHealthcare',
    procedure_raw: 'Breast reconstruction revision care',
    procedure_normalized: 'Breast reconstruction revision care',
    denial_reason_raw: 'Reconstruction revision denied repeatedly despite documentation',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 90,
    is_low_signal: false,
    fingerprint: 'bco-insurance-denial-002',
  },
  {
    observation_id: 'bbb-uhg-complaints-001',
    canonical_url: 'https://www.bbb.org/us/mn/minnetonka/profile/health-insurance/unitedhealth-group-0704-21000358/complaints',
    source_type: 'complaint_platform',
    source_label: 'BBB Complaints',
    source_weight: 'complaint_platform',
    title: 'UnitedHealth Group complaints',
    raw_text: 'BBB complaint listing includes denied claims, delays, nonresponse, and escalation narratives for UnitedHealth Group.',
    story_excerpt: 'Complaint-platform signal for repeated administrative and claim-payment failure patterns.',
    insurer_raw: 'UnitedHealth Group',
    insurer_normalized: 'UnitedHealthcare',
    procedure_raw: 'Claims processing and coverage disputes',
    procedure_normalized: 'Claims processing disputes',
    denial_reason_raw: 'Denied claims, delay, and insufficient response',
    denial_category: 'Administrative',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 72,
    is_low_signal: false,
    fingerprint: 'bbb-uhg-complaints-001',
  },
  {
    observation_id: 'ca-uhg-medicare-probe-001',
    canonical_url: 'https://www.consumeraffairs.com/news/feds-probing-unitedhealth-groups-medicare-billing-practices-reports-say-022425.html',
    source_type: 'investigative',
    source_label: 'ConsumerAffairs News',
    source_weight: 'investigative',
    title: 'UnitedHealth Medicare billing probe',
    raw_text: 'ConsumerAffairs report about federal scrutiny of UnitedHealth Medicare billing practices and broader Medicare Advantage concerns.',
    story_excerpt: 'Useful for insurer scrutiny context and Medicare Advantage anomaly framing.',
    insurer_raw: 'UnitedHealth Group',
    insurer_normalized: 'UnitedHealthcare',
    procedure_raw: 'Medicare Advantage billing practices',
    procedure_normalized: 'Medicare Advantage billing practices',
    denial_reason_raw: 'Questionable Medicare Advantage billing and scrutiny',
    denial_category: 'Administrative',
    plan_type: 'Medicare Advantage',
    erisa_status: 'Non-ERISA',
    quality_score: 70,
    is_low_signal: false,
    fingerprint: 'ca-uhg-medicare-probe-001',
  },
  {
    observation_id: 'als-bill-rights-001',
    canonical_url: 'https://www.als.org/sites/default/files/2020-04/FYI_patient%20bill_of_rights.pdf',
    source_type: 'official_regulatory',
    source_label: 'The ALS Association',
    source_weight: 'official_regulatory',
    title: 'ALS patient bill of rights',
    raw_text: 'ALS Association patient bill of rights notes rights to understandable benefit information, exclusions, appeal procedures, and coverage clarity for home care, hospice, and nursing home care.',
    story_excerpt: 'Excellent benchmark source for appeals and coverage rights in ALS care.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'ALS home care, hospice, nursing support',
    procedure_normalized: 'ALS supportive care coverage',
    denial_reason_raw: 'Coverage exclusions and appeal rights disputes',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 89,
    is_low_signal: false,
    fingerprint: 'als-bill-rights-001',
  },
  {
    observation_id: 'alz-insurance-001',
    canonical_url: 'https://www.alz.org/Help-Support/Caregiving/Financial-Legal-Planning/Insurance',
    source_type: 'official_regulatory',
    source_label: "Alzheimer's Association",
    source_weight: 'official_regulatory',
    title: 'Insurance and care coverage for dementia',
    raw_text: 'Alzheimer’s Association resource on Medicare, Medicaid, long-term care insurance, and private coverage for dementia care.',
    story_excerpt: 'Benchmark source for dementia care coverage and caregiver financial strain.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Dementia care and long-term support',
    procedure_normalized: 'Dementia care and long-term support',
    denial_reason_raw: 'Coverage limitations for long-term dementia care',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 87,
    is_low_signal: false,
    fingerprint: 'alz-insurance-001',
  },
  {
    observation_id: 'cms-prior-auth-rule-001',
    canonical_url: 'https://www.cms.gov/newsroom/press-releases/cms-finalizes-rule-expand-access-health-information-and-improve-prior-authorization-process',
    source_type: 'official_regulatory',
    source_label: 'CMS',
    source_weight: 'official_regulatory',
    title: 'CMS prior authorization final rule',
    raw_text: 'CMS final rule on prior authorization transparency, API exchange, and decision timelines.',
    story_excerpt: 'Ground-truth benchmark for prior auth process expectations.',
    insurer_raw: 'Impacted payers',
    insurer_normalized: 'Impacted payers',
    procedure_raw: 'Electronic prior authorization workflows',
    procedure_normalized: 'Prior authorization workflows',
    denial_reason_raw: 'Delayed or opaque prior authorization decisioning',
    denial_category: 'Prior Authorization',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 92,
    is_low_signal: false,
    fingerprint: 'cms-prior-auth-rule-001',
  },
  {
    observation_id: 'kff-marketplace-denials-001',
    canonical_url: 'https://www.kff.org/private-insurance/issue-brief/claims-denials-and-appeals-in-aca-marketplace-plans/',
    source_type: 'official_regulatory',
    source_label: 'KFF',
    source_weight: 'official_regulatory',
    title: 'Claims denials and appeals in ACA marketplace plans',
    raw_text: 'KFF analysis of marketplace insurer disclosures showing substantial claims denials and low appeal rates.',
    story_excerpt: 'High-value benchmark source for claims denial rates and low appeal usage.',
    insurer_raw: 'ACA marketplace insurers',
    insurer_normalized: 'ACA marketplace insurers',
    procedure_raw: 'In-network claims across plans',
    procedure_normalized: 'Marketplace claims',
    denial_reason_raw: 'Claim denial rates and low appeal uptake',
    denial_category: 'Administrative',
    plan_type: 'Marketplace',
    erisa_status: 'Non-ERISA',
    quality_score: 90,
    is_low_signal: false,
    fingerprint: 'kff-marketplace-denials-001',
  },
  {
    observation_id: 'oig-ma-denials-001',
    canonical_url: 'https://oig.hhs.gov/reports/all/2022/some-medicare-advantage-organization-denials-of-prior-authorization-requests-raise-concerns-about-beneficiary-access-to-care/',
    source_type: 'official_regulatory',
    source_label: 'HHS OIG',
    source_weight: 'official_regulatory',
    title: 'Medicare Advantage denials raise concerns about beneficiary access',
    raw_text: 'HHS OIG report finding some Medicare Advantage denials met Medicare coverage rules and should not have been denied.',
    story_excerpt: 'One of the strongest official benchmark sources for wrongful denials.',
    insurer_raw: 'Medicare Advantage organizations',
    insurer_normalized: 'Medicare Advantage organizations',
    procedure_raw: 'Prior authorization requests and payment decisions',
    procedure_normalized: 'Prior authorization requests and payment decisions',
    denial_reason_raw: 'Coverage denials on requests that met Medicare rules',
    denial_category: 'Medical Necessity',
    plan_type: 'Medicare Advantage',
    erisa_status: 'Non-ERISA',
    quality_score: 95,
    is_low_signal: false,
    fingerprint: 'oig-ma-denials-001',
  },
  {
    observation_id: 'paf-start-001',
    canonical_url: 'https://www.patientadvocate.org/explore-our-resources/insurance-denials-appeals/where-to-start-if-insurance-has-denied-your-service-and-will-not-pay/',
    source_type: 'official_regulatory',
    source_label: 'Patient Advocate Foundation',
    source_weight: 'official_regulatory',
    title: 'Where to start if insurance denied your service',
    raw_text: 'Patient Advocate Foundation guidance for consumers after service denial with immediate action steps.',
    story_excerpt: 'Useful operational source for appeal support and taxonomy.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Denied service appeal',
    procedure_normalized: 'Denied service appeal',
    denial_reason_raw: 'Insurance denied service and will not pay',
    denial_category: 'Administrative',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 84,
    is_low_signal: false,
    fingerprint: 'paf-start-001',
  },
  {
    observation_id: 'reddit-healthinsurance-001',
    canonical_url: 'https://www.reddit.com/r/HealthInsurance/comments/1o87rqd/have_you_ever_had_your_health_insurance_denials/',
    source_type: 'public_patient_forum',
    source_label: 'Reddit r/HealthInsurance',
    source_weight: 'public_patient_forum',
    title: 'Have you ever had your health insurance denials overturned',
    raw_text: 'Reddit discussion focused directly on denial overturn outcomes and appeals experience.',
    story_excerpt: 'High-value community thread for appeal outcome language.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Health insurance denial appeals',
    procedure_normalized: 'Health insurance denial appeals',
    denial_reason_raw: 'Denials overturned on appeal',
    denial_category: 'Administrative',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 81,
    is_low_signal: false,
    fingerprint: 'reddit-healthinsurance-001',
  },
  {
    observation_id: 'stat-navihealth-001',
    canonical_url: 'https://www.statnews.com/2023/11/14/unitedhealth-navihealth-lawsuit-medicare-advantage/',
    source_type: 'investigative',
    source_label: 'STAT News',
    source_weight: 'investigative',
    title: 'UnitedHealth NaviHealth Medicare Advantage reporting',
    raw_text: 'STAT reporting on allegations that algorithmic tools influenced post-acute care coverage limits and denials.',
    story_excerpt: 'Strong systemic signal for algorithmic and post-acute care denials.',
    insurer_raw: 'UnitedHealthcare',
    insurer_normalized: 'UnitedHealthcare',
    procedure_raw: 'Skilled nursing and post-acute care coverage',
    procedure_normalized: 'Skilled nursing and post-acute care coverage',
    denial_reason_raw: 'Algorithm-guided early discharge or denial pressure',
    denial_category: 'Medical Necessity',
    plan_type: 'Medicare Advantage',
    erisa_status: 'Non-ERISA',
    quality_score: 90,
    is_low_signal: false,
    fingerprint: 'stat-navihealth-001',
  },
  {
    observation_id: 'propublica-cigna-pxdx-002',
    canonical_url: 'https://www.propublica.org/article/cigna-pxdx-medical-review-denial-errors',
    source_type: 'investigative',
    source_label: 'ProPublica',
    source_weight: 'investigative',
    title: 'Cigna PXDX denial errors',
    raw_text: 'ProPublica investigation into Cigna PXDX and denial errors without individualized review.',
    story_excerpt: 'High-signal systemic denial source.',
    insurer_raw: 'Cigna',
    insurer_normalized: 'Cigna',
    procedure_raw: 'Bulk claim review workflow',
    procedure_normalized: 'Bulk claim review workflow',
    denial_reason_raw: 'Automated claim rejection without individualized review',
    denial_category: 'Administrative',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 94,
    is_low_signal: false,
    fingerprint: 'propublica-cigna-pxdx-002',
  },
  {
    observation_id: 'oac-access-obesity-care-001',
    canonical_url: 'https://www.obesityaction.org/action-through-advocacy/access-to-care/access-to-obesity-care-and-treatments/',
    source_type: 'official_regulatory',
    source_label: 'Obesity Action Coalition',
    source_weight: 'official_regulatory',
    title: 'Access to obesity care and treatments',
    raw_text: 'Obesity Action Coalition resource focused on insurance coverage barriers, exclusions, and access problems for obesity care and anti-obesity medications.',
    story_excerpt: 'Strong benchmark source for GLP-1, obesity treatment, and coverage exclusion battles.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Obesity care and anti-obesity medication coverage',
    procedure_normalized: 'GLP-1 medication',
    denial_reason_raw: 'Coverage exclusion and prior authorization barriers for obesity treatment',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 90,
    is_low_signal: false,
    fingerprint: 'oac-access-obesity-care-001',
  },
  {
    observation_id: 'cancercare-insurance-costs-001',
    canonical_url: 'https://www.cancercare.org/publications/62-understanding_the_cost_of_care_and_your_health_insurance',
    source_type: 'official_regulatory',
    source_label: 'CancerCare',
    source_weight: 'official_regulatory',
    title: 'Understanding the cost of care and your health insurance',
    raw_text: 'CancerCare guidance on oncology treatment costs, prior authorization barriers, claim denials, and insurance navigation for patients undergoing cancer treatment.',
    story_excerpt: 'Useful benchmark source for cancer-treatment access, financial toxicity, and appeal support.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Cancer treatment and oncology supportive care',
    procedure_normalized: 'Cancer treatment and oncology care',
    denial_reason_raw: 'Coverage barriers and prior authorization friction in cancer care',
    denial_category: 'Prior Authorization',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 89,
    is_low_signal: false,
    fingerprint: 'cancercare-insurance-costs-001',
  },
  {
    observation_id: 'autism-speaks-aba-appeal-001',
    canonical_url: 'https://www.autismspeaks.org/tool-kit-excerpt/what-if-my-insurance-company-denies-coverage',
    source_type: 'official_regulatory',
    source_label: 'Autism Speaks',
    source_weight: 'official_regulatory',
    title: 'What if my insurance company denies coverage',
    raw_text: 'Autism Speaks guidance focused on insurer denials for autism-related services and what families can do when ABA or related care is denied.',
    story_excerpt: 'High-value source for autism therapy denials, mandate navigation, and family appeals.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Autism therapy and ABA coverage',
    procedure_normalized: 'Autism therapy',
    denial_reason_raw: 'Autism service denial and coverage disputes',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 91,
    is_low_signal: false,
    fingerprint: 'autism-speaks-aba-appeal-001',
  },
  {
    observation_id: 'nami-insurance-mental-health-001',
    canonical_url: 'https://www.nami.org/Your-Journey/Individuals-with-Mental-Illness/Getting-Mental-Health-Support/Understanding-Health-Insurance',
    source_type: 'official_regulatory',
    source_label: 'NAMI',
    source_weight: 'official_regulatory',
    title: 'Understanding health insurance for mental health support',
    raw_text: 'NAMI overview of mental health coverage, in-network vs out-of-network access, appeals, and understanding behavioral-health benefits.',
    story_excerpt: 'Useful benchmark source for depression, anxiety, therapy, psychiatry, and behavioral-health insurance barriers.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Therapy services and psychiatric care',
    procedure_normalized: 'Therapy services',
    denial_reason_raw: 'Mental health coverage limitation or access dispute',
    denial_category: 'Out of Network',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 88,
    is_low_signal: false,
    fingerprint: 'nami-insurance-mental-health-001',
  },
  {
    observation_id: 'nami-parity-001',
    canonical_url: 'https://www.nami.org/Advocacy/Policy-Priorities/Improving-Health/Mental-Health-Parity',
    source_type: 'official_regulatory',
    source_label: 'NAMI',
    source_weight: 'official_regulatory',
    title: 'Mental health parity',
    raw_text: 'NAMI mental health parity policy overview explaining why insurers cannot treat behavioral health benefits more restrictively than medical care.',
    story_excerpt: 'Important benchmark source for mental health parity arguments in therapy and psychiatric medication denials.',
    insurer_raw: 'Multiple insurers',
    insurer_normalized: 'Multiple insurers',
    procedure_raw: 'Mental health and behavioral health coverage',
    procedure_normalized: 'Therapy services',
    denial_reason_raw: 'Parity violation or restrictive mental health coverage',
    denial_category: 'Coverage Exclusion',
    plan_type: 'Unknown',
    erisa_status: 'Unknown',
    quality_score: 90,
    is_low_signal: false,
    fingerprint: 'nami-parity-001',
  }
];

async function main() {
  const { projectId, accessToken } = await getBigQueryAccessToken();
  const rows = observations.map((observation) => ({
    insertId: observation.observation_id,
    json: {
      ...observation,
      ingested_at: new Date().toISOString(),
    },
  }));

  const response = await fetch(
    `https://bigquery.googleapis.com/bigquery/v2/projects/${projectId}/datasets/${DATASET_ID}/tables/${TABLE_ID}/insertAll`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        kind: 'bigquery#tableDataInsertAllRequest',
        skipInvalidRows: false,
        ignoreUnknownValues: false,
        rows,
      }),
    }
  );

  const text = await response.text();
  if (!response.ok) {
    throw new Error(`Failed to insert expanded public pack: ${response.status} ${text}`);
  }

  console.log(JSON.stringify({ inserted: observations.length }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
